# Pipeline Crawling Data Piksel Sentinel-2A via openEO CDSE (Jawa Timur)
## Ekstraksi Spektral Multiband (B02, B03, B04, B05, B08, B11, B12, NDVI, NDWI, MNDWI, NDBI, REMI, NDMI, BSI) per Piksel Poligon

---

### Deskripsi Alur Kerja
Notebook ini mengeksekusi pipeline pengunduhan dan pemrosesan piksel satelit multispektral skala besar dari **Copernicus Data Space Ecosystem (CDSE) openEO**:
1. **Membaca Sampel Poligon:** Memuat 250 poligon sampel hasil digitasi (5 kelas @ 50 poligon).
2. **Tiling Grid Spasial:** Membagi poligon sampel ke dalam grid *tile* kecil (~22 km x 22 km) agar lolos batas ukuran pemrosesan openEO dan meminimalisir kuota.
3. **Pengiriman Batch Job:** Mengirim job pemrosesan ke server openEO CDSE dengan masking awan berbasis band SCL (*Scene Classification Layer*).
4. **Ekstraksi Piksel & Indeks:** Mengunduh GeoTIFF hasil job, mengekstraksi piksel di dalam poligon sampel, menghitung indeks spektral (`NDVI`, `NDWI`, `MNDWI`, `NDBI`), dan mengekspor hasilnya ke file CSV `piksel_s2.csv`.

In [18]:
# 1. Import Dependensi Utama
import os
import time
import threading
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio.windows import Window
from rasterio.mask import mask as rio_mask
from rasterio.features import rasterize
from rasterio.warp import transform as warp_transform
from shapely.geometry import box
from shapely.validation import make_valid

import openeo
from openeo.extra.job_management import CsvJobDatabase, MultiBackendJobManager

print("[OK] Semua library dependensi berhasil di-import!")

[OK] Semua library dependensi berhasil di-import!

In [19]:
# 2. Konfigurasi Parameter & Deteksi Path Otomatis
# (Mendeteksi direktori dengan aman baik dijalankan dari folder 'uts/code' maupun root workspace)
cwd = Path.cwd()
if (cwd / "uts" / "data").exists():
    ROOT_UTS = cwd / "uts"
elif (cwd.parent / "data").exists() and cwd.name == "code":
    ROOT_UTS = cwd.parent
elif (cwd / "data").exists():
    ROOT_UTS = cwd
else:
    ROOT_UTS = Path("../").resolve()

GEOJSON_DIR = ROOT_UTS / "data" / "geojson"
OUT_DIR = ROOT_UTS / "data" / "csv" / "hasil_s2_piksel"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Definisi Sumber File Sampel Poligon (Mendukung .zip maupun .geojson)
SUMBER = {}
kelas_config = [
    ("Sawah", 1, "sawah.zip", "jawatimur_Sawah.geojson"),
    ("Pemukiman", 2, "pemukiman.zip", "jawatimur_Pemukiman.geojson"),
    ("Hutan Non-Mangrove", 3, "hutan_non_mangrove.zip", "jawatimur_Hutan_non_mangrove.geojson"),
    ("Air", 4, "air.zip", "jawatimur_Air.geojson"),
    ("Hutan Mangrove", 5, "hutan_mangrove.zip", "jawatimur_Hutan_mangrove.geojson"),
]

for nama_kelas, kode_label, zip_name, geojson_name in kelas_config:
    zip_path = GEOJSON_DIR / zip_name
    geojson_path = GEOJSON_DIR / geojson_name
    if zip_path.exists():
        SUMBER[nama_kelas] = (str(zip_path), kode_label)
    elif geojson_path.exists():
        SUMBER[nama_kelas] = (str(geojson_path), kode_label)
    else:
        SUMBER[nama_kelas] = (str(zip_path), kode_label)

# Parameter Grid Tiling & Satelit
TILE_DEG = 0.05          # Ukuran grid tile lebih kecil ~5.5 km x 5.5 km (~550x550 piksel @10m)
BUFFER_DEG = 0.002       # Buffer margin ~200 meter di sekeliling batas poligon
TANGGAL = ["2024-08-01", "2024-08-31"]   # Rentang waktu observasi musim kemarau (minim awan)
BANDS = ["B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B8A", "B09", "B11", "B12"]  # Seluruh 12 Band Spektral Sentinel-2 L2A
PAKAI_MASK_SCL = True    # Masking awan/bayangan per piksel via band SCL
MAX_CLOUD = 30           # Batas toleransi tutupan awan scene (%)
PARALEL = 2              # Jumlah job konkuren (akun CDSE gratis max 2)

# Parameter Ekstraksi Piksel
MAKS_PIKSEL_PER_POLIGON = 2000  # Kuota maksimal piksel per poligon sampel (mencegah file CSV membengkak)
SEED = 42
BUAT_RASTER_LABEL = True        # Buat label_<tile>.tif di folder masing-masing job

JOB_DB_PATH = OUT_DIR / "daftar_job.csv"
PETA_CSV = OUT_DIR / "peta_sampel_tile.csv"
PIKSEL_OUT = OUT_DIR / "piksel_s2.csv"

print(f"Direktori GeoJSON : {GEOJSON_DIR}")
print(f"Direktori Output  : {OUT_DIR}")
print(f"Target Output CSV : {PIKSEL_OUT}")

Direktori GeoJSON : d:\SEMESTER 5 TIF 2026\PSD\mynewbook\uts\data\geojson
Direktori Output  : d:\SEMESTER 5 TIF 2026\PSD\mynewbook\uts\data\csv\hasil_s2_piksel
Target Output CSV : d:\SEMESTER 5 TIF 2026\PSD\mynewbook\uts\data\csv\hasil_s2_piksel\piksel_s2.csv

---
## Step 1: Memuat & Menggabungkan Poligon Sampel 5 Kelas Tutupan Lahan

In [20]:
def baca_semua() -> gpd.GeoDataFrame:
    """Membaca semua file poligon sampel dan menggabungkannya ke dalam GeoDataFrame WGS84."""
    bagian = []
    for nama, (file_path, label) in SUMBER.items():
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File sampel untuk '{nama}' tidak ditemukan di: {file_path}")
            
        g = gpd.read_file(file_path).to_crs("EPSG:4326")
        g["poligon_no"] = np.arange(len(g))
        g = g[g.geometry.notna() & ~g.geometry.is_empty].copy()
        g["geometry"] = g.geometry.apply(lambda x: x if x.is_valid else make_valid(x))
        g["label_teks"] = nama
        g["label"] = label
        g["poligon_id"] = [f"{nama}_{n:04d}" for n in g["poligon_no"]]
        g = g[["poligon_id", "poligon_no", "label", "label_teks", "geometry"]]
        print(f"Kelas: {nama:<18} | Jumlah: {len(g):>3} poligon | Bounds: {[round(v, 2) for v in g.total_bounds]}")
        bagian.append(g)

    gdf = gpd.GeoDataFrame(pd.concat(bagian, ignore_index=True), crs="EPSG:4326")
    print("-" * 60)
    print(f"Total Keseluruhan Sampel: {len(gdf)} Poligon")
    return gdf

gdf_sampel = baca_semua()
gdf_sampel.head(3)

Kelas: Sawah              | Jumlah:  50 poligon | Bounds: [np.float64(112.55), np.float64(-7.07), np.float64(112.59), np.float64(-7.06)]
Kelas: Pemukiman          | Jumlah:  50 poligon | Bounds: [np.float64(112.55), np.float64(-7.06), np.float64(112.59), np.float64(-7.04)]
Kelas: Hutan Non-Mangrove | Jumlah:  50 poligon | Bounds: [np.float64(111.21), np.float64(-8.19), np.float64(112.52), np.float64(-7.62)]
Kelas: Air                | Jumlah:  50 poligon | Bounds: [np.float64(111.21), np.float64(-7.68), np.float64(112.78), np.float64(-6.65)]
Kelas: Hutan Mangrove     | Jumlah:  50 poligon | Bounds: [np.float64(112.69), np.float64(-7.39), np.float64(113.53), np.float64(-7.14)]
------------------------------------------------------------
Total Keseluruhan Sampel: 250 Poligon

,poligon_id,poligon_no,label,label_teks,geometry
0,Sawah_0000,0,1,Sawah,"POLYGON ((112.5461 -7.0686, 112.54624 -7.0686,..."
1,Sawah_0001,1,1,Sawah,"POLYGON ((112.58605 -7.07168, 112.58617 -7.071..."
2,Sawah_0002,2,1,Sawah,"POLYGON ((112.58179 -7.0716, 112.5819 -7.07168..."

---
## Step 2: Pembagian Grid Tile Spasial (*Tiling System*)

Poligon sampel dipecah dan dipetakan ke dalam grid tile `x{gx}_y{gy}` berukuran 0.20° (~22 km) agar openEO memproses tiap area secara modular tanpa memicu *memory limit*.

In [21]:
def buat_tile(gdf: gpd.GeoDataFrame):
    T, B = TILE_DEG, BUFFER_DEG
    peta, batas, sel_xy = [], {}, {}

    for idx, geom in gdf.geometry.items():
        minx, miny, maxx, maxy = geom.bounds
        for gx in range(int(np.floor(minx / T)), int(np.floor(maxx / T)) + 1):
            for gy in range(int(np.floor(miny / T)), int(np.floor(maxy / T)) + 1):
                sel = box(gx * T, gy * T, (gx + 1) * T, (gy + 1) * T)
                if not geom.intersects(sel):
                    continue
                bagian = geom.intersection(sel)
                if bagian.is_empty:
                    continue
                b = bagian.bounds
                tid = f"x{gx}_y{gy}"
                peta.append({"tile_id": tid, "sampel_id": idx, "poligon_id": gdf.at[idx, "poligon_id"]})
                sel_xy[tid] = (gx, gy)
                if tid in batas:
                    o = batas[tid]
                    batas[tid] = (min(o[0], b[0]), min(o[1], b[1]), max(o[2], b[2]), max(o[3], b[3]))
                else:
                    batas[tid] = b

    tiles = pd.DataFrame([
        {
            "tile_id": tid,
            "gx": sel_xy[tid][0],
            "gy": sel_xy[tid][1],
            "west": b[0] - B,
            "south": b[1] - B,
            "east": b[2] + B,
            "north": b[3] + B,
        }
        for tid, b in batas.items()
    ])
    peta = pd.DataFrame(peta)
    tiles["n_sampel"] = tiles["tile_id"].map(peta.groupby("tile_id")["sampel_id"].nunique())

    lebar_km = (tiles.east - tiles.west) * 111.32 * np.cos(np.radians((tiles.north + tiles.south) / 2))
    tinggi_km = (tiles.north - tiles.south) * 110.57
    print(f"Total Grid Tile (Job)   : {len(tiles)} Tile")
    print(f"Ukuran Tile Terbesar    : {lebar_km.max():.1f} km x {tinggi_km.max():.1f} km")
    print(f"Total Estimasi Area     : {(lebar_km * tinggi_km).sum():,.0f} km²")
    return tiles, peta

tiles_df, peta_df = buat_tile(gdf_sampel)
tiles_df.head(3)

Total Grid Tile (Job)   : 97 Tile
Ukuran Tile Terbesar    : 6.0 km x 6.0 km
Total Estimasi Area     : 1,429 km²

       tile_id    gx   gy        west     south        east   north  n_sampel
0  x2250_y-142  2250 -142  112.544038 -7.071343  112.552000 -7.0480         2
1  x2251_y-142  2251 -142  112.548000 -7.075640  112.589210 -7.0480        88
2  x2251_y-141  2251 -141  112.548000 -7.052000  112.581202 -7.0166        29

---
## Step 3: Pengiriman & Pemantauan Batch Job openEO CDSE

Koneksi otomatis ke `https://openeo.dataspace.copernicus.eu` menggunakan protokol OIDC. Status progres tiap job disimpan ke `daftar_job.csv` sehingga jika terjadi interupsi, job yang sudah selesai tidak akan diulang kembali.

In [22]:
def _jam() -> str:
    return datetime.now().strftime("%H:%M:%S")

def start_job(row, connection, **kwargs):
    print(f"[{_jam()}] >> Mengirim job tile {row['tile_id']} ({row.get('n_sampel', '?')} poligon)...", flush=True)
    bbox = {
        "west": float(row["west"]),
        "south": float(row["south"]),
        "east": float(row["east"]),
        "north": float(row["north"]),
    }
    bands = BANDS + ["SCL"] if PAKAI_MASK_SCL else BANDS
    cube = connection.load_collection(
        "SENTINEL2_L2A",
        spatial_extent=bbox,
        temporal_extent=TANGGAL,
        bands=bands,
        max_cloud_cover=MAX_CLOUD,
    )

    if PAKAI_MASK_SCL:
        scl = cube.band("SCL")
        # Masking piksel jenuh, bayangan awan, awan sedang/tinggi, dan cirrus
        mask_awan = (scl == 1) | (scl == 3) | (scl == 8) | (scl == 9) | (scl == 10)
        cube = cube.filter_bands(BANDS).mask(mask_awan)

    komposit = cube.median_time()
    return komposit.create_job(title=f"s2_{row['tile_id']}", out_format="GTiff")

class ManagerBerlapor(MultiBackendJobManager):
    def on_job_done(self, job, row):
        print(f"[{_jam()}] [OK] Tile {row['tile_id']} selesai (job {job.job_id}), mengunduh hasil...", flush=True)
        super().on_job_done(job, row)
        print(f"[{_jam()}] [OK] Tile {row['tile_id']} berhasil terunduh.", flush=True)

    def on_job_error(self, job, row):
        print(f"[{_jam()}] [ERROR] Tile {row['tile_id']} gagal (job {job.job_id}).", flush=True)
        super().on_job_error(job, row)

def _lapor_berkala(job_db, berhenti: threading.Event, interval: int = 30):
    mulai = time.time()
    while not berhenti.wait(interval):
        try:
            df = job_db.read()
        except Exception:
            continue
        n = len(df)
        hitung = df["status"].value_counts().to_dict()
        selesai = hitung.get("finished", 0)
        gagal = sum(hitung.get(s, 0) for s in ("error", "start_failed", "skipped"))
        jalan = hitung.get("running", 0) + hitung.get("queued", 0) + hitung.get("created", 0)
        belum = hitung.get("not_started", 0)
        persen = 100 * selesai / n if n else 0
        menit = (time.time() - mulai) / 60
        print(f"[{_jam()}] Progres: {selesai}/{n} ({persen:.0f}%) | Berjalan/Antre: {jalan} | Belum: {belum} | Gagal: {gagal} | {menit:.1f} mnt", flush=True)

def jalankan_job(tiles: pd.DataFrame, ulangi_error: bool = True):
    conn = openeo.connect("https://openeo.dataspace.copernicus.eu")
    conn.authenticate_oidc()

    manager = ManagerBerlapor(root_dir=OUT_DIR, poll_sleep=30)
    manager.add_backend("cdse", connection=conn, parallel_jobs=PARALEL)

    job_db = CsvJobDatabase(JOB_DB_PATH)
    if not job_db.exists():
        job_db.initialize_from_df(tiles)
    elif ulangi_error:
        df = job_db.read()
        gagal = df["status"].isin(["error", "start_failed", "skipped"])
        if gagal.any():
            print(f"Mengulang {int(gagal.sum())} job yang sebelumnya gagal.")
            df.loc[gagal, "status"] = "not_started"
            job_db.persist(df)

    berhenti = threading.Event()
    pemantau = threading.Thread(target=_lapor_berkala, args=(job_db, berhenti), daemon=True)
    pemantau.start()
    try:
        manager.run_jobs(start_job=start_job, job_db=job_db)
    finally:
        berhenti.set()
        pemantau.join(timeout=5)

    df = job_db.read()
    print("\n=== RINGKASAN STATUS JOB OPENEO ===")
    print(df["status"].value_counts().to_string())
    return df

---
## Step 4: Ekstraksi Piksel Berlabel & Kalkulasi Indeks Spektral

Membaca GeoTIFF tiap tile hasil unduhan, mengekstraksi piksel yang beririsan dengan poligon sampel, menghitung nilai `NDVI`, `NDWI`, `MNDWI`, `NDBI`, dan menyimpan dataset final ke `piksel_s2.csv`.

In [23]:
def _nama_band(src) -> list:
    desc = list(src.descriptions or [])
    if len(desc) == src.count and all(desc) and set(BANDS) <= set(desc):
        return desc
    return BANDS

def _valid_mask(data, nodata, masked=None):
    ok = np.isfinite(data).all(axis=0) & (data > 0).all(axis=0)
    if nodata is not None and not np.isnan(nodata):
        ok &= ~(data == nodata).any(axis=0)
    if masked is not None:
        ok &= ~masked
    return ok

def _piksel_geom(src, geom):
    nodata = src.nodata
    if geom.geom_type == "Point":
        rr, cc = src.index(geom.x, geom.y)
        if not (0 <= rr < src.height and 0 <= cc < src.width):
            return None
        data = src.read(window=Window(cc, rr, 1, 1)).astype("float64")
        ok = _valid_mask(data, nodata)
        row0, col0 = rr, cc
    else:
        ok = None
        for all_touched in (False, True):
            try:
                arr, tr = rio_mask(src, [geom], crop=True, all_touched=all_touched, filled=False)
            except ValueError:
                return None
            data = np.ma.getdata(arr).astype("float64")
            ok = _valid_mask(data, nodata, np.ma.getmaskarray(arr).any(axis=0))
            row0 = int(round((tr.f - src.transform.f) / src.transform.e))
            col0 = int(round((tr.c - src.transform.c) / src.transform.a))
            if ok.any():
                break
        if ok is None or not ok.any():
            return None

    r_idx, c_idx = np.nonzero(ok)
    if len(r_idx) == 0:
        return None
    nilai = data[:, r_idx, c_idx]
    px_row, px_col = row0 + r_idx, col0 + c_idx
    xs, ys = rasterio.transform.xy(src.transform, px_row, px_col)
    return nilai, px_row, px_col, np.asarray(xs), np.asarray(ys)

def tambah_indeks(df: pd.DataFrame) -> pd.DataFrame:
    e = 1e-9
    # 1. Indeks Vegetasi Dasar
    if "B08" in df.columns and "B04" in df.columns:
        df["NDVI"] = (df["B08"] - df["B04"]) / (df["B08"] + df["B04"] + e)
    # 2. Indeks Air
    if "B03" in df.columns and "B08" in df.columns:
        df["NDWI"] = (df["B03"] - df["B08"]) / (df["B03"] + df["B08"] + e)
    if "B03" in df.columns and "B11" in df.columns:
        df["MNDWI"] = (df["B03"] - df["B11"]) / (df["B03"] + df["B11"] + e)
    # 3. Indeks Kawasan Terbangun
    if "B11" in df.columns and "B08" in df.columns:
        df["NDBI"] = (df["B11"] - df["B08"]) / (df["B11"] + df["B08"] + e)
    # 4. REMI (Red-Edge Mangrove Index - Chen et al., 2023) Menggunakan B05 Asli
    if "B05" in df.columns and "B04" in df.columns and "B11" in df.columns and "B03" in df.columns:
        remi_den = df["B11"] - df["B03"]
        remi_den_safe = np.where(np.abs(remi_den) < 1.0, np.sign(remi_den + 1e-9) * 1.0, remi_den)
        df["REMI"] = np.clip((df["B05"] - df["B04"]) / remi_den_safe, -3.0, 3.0)
    # 5. NDMI / LSWI (Kelembapan Kanopi & Sawah Irigasi)
    if "B08" in df.columns and "B11" in df.columns:
        df["NDMI"] = (df["B08"] - df["B11"]) / (df["B08"] + df["B11"] + e)
    # 6. BSI (Bare Soil Index - Lahan Sawah Kering vs Pemukiman)
    if all(b in df.columns for b in ["B11", "B04", "B08", "B02"]):
        df["BSI"] = ((df["B11"] + df["B04"]) - (df["B08"] + df["B02"])) / ((df["B11"] + df["B04"]) + (df["B08"] + df["B02"]) + e)
    return df

def _tif_tile(r):
    tifs = sorted(p for p in OUT_DIR.glob(f"job_{r['id']}/*.tif") if not p.name.startswith("label_"))
    return tifs[0] if tifs else None

def ekstrak_piksel(gdf, db, peta) -> pd.DataFrame:
    rng = np.random.default_rng(SEED)
    T = TILE_DEG
    potongan = []
    selesai = db[db["status"] == "finished"]
    print(f"\nMengekstrak piksel dari {len(selesai)} tile yang telah selesai...")

    total_tile = len(selesai)
    total_piksel = 0
    t0 = time.time()

    for no_tile, (_, r) in enumerate(selesai.iterrows(), start=1):
        tif = _tif_tile(r)
        if tif is None:
            continue

        cx0, cy0 = int(r["gx"]) * T, int(r["gy"]) * T
        ids = peta.loc[peta["tile_id"] == r["tile_id"], "sampel_id"].unique()
        n_poli = len(ids)
        piksel_tile = 0

        with rasterio.open(tif) as src:
            nama_band = _nama_band(src)
            sub_r = gdf.loc[ids].to_crs(src.crs)

            for no_poli, (idx, row) in enumerate(sub_r.iterrows(), start=1):
                hasil = _piksel_geom(src, row.geometry)
                if hasil is None:
                    continue
                nilai, px_row, px_col, xs, ys = hasil

                lon, lat = warp_transform(src.crs, "EPSG:4326", xs.tolist(), ys.tolist())
                lon, lat = np.asarray(lon), np.asarray(lat)

                pilih = np.flatnonzero((lon >= cx0) & (lon < cx0 + T) & (lat >= cy0) & (lat < cy0 + T))
                if len(pilih) == 0:
                    continue
                if MAKS_PIKSEL_PER_POLIGON and len(pilih) > MAKS_PIKSEL_PER_POLIGON:
                    pilih = rng.choice(pilih, MAKS_PIKSEL_PER_POLIGON, replace=False)

                d = {
                    "poligon_id": row["poligon_id"],
                    "poligon_no": row["poligon_no"],
                    "sampel_id": idx,
                    "tile_id": r["tile_id"],
                    "label": row["label"],
                    "label_teks": row["label_teks"],
                    "px_row": px_row[pilih],
                    "px_col": px_col[pilih],
                    "lon": lon[pilih],
                    "lat": lat[pilih],
                }
                for i, nb in enumerate(nama_band):
                    d[nb] = nilai[i, pilih]
                potongan.append(pd.DataFrame(d))
                piksel_tile += len(pilih)
                total_piksel += len(pilih)

        print(f"[{_jam()}] Tile {no_tile}/{total_tile} ({r['tile_id']}): {piksel_tile:,} piksel diekstrak", flush=True)

    if not potongan:
        print("Tidak ada piksel yang berhasil diekstrak.")
        return pd.DataFrame()

    df = pd.concat(potongan, ignore_index=True)
    kunci = ["tile_id", "px_row", "px_col"]
    df = df.drop_duplicates(kunci).reset_index(drop=True)
    df = tambah_indeks(df)

    df.to_csv(PIKSEL_OUT, index=False)
    print(f"\n[SUKSES] Dataset piksel tersimpan ke: {PIKSEL_OUT}")
    print(f"Total Piksel Berlabel: {len(df):,}")
    print(df.groupby("label_teks").size().to_string())
    return df

---
## Step 5: Eksekusi Pipeline Crawling & Ekstraksi Piksel

Jalankan fungsi utama berikut:
- `jalankan=True`: Kirim dan pantau batch job ke server CDSE openEO.
- `ekstrak=True`: Ekstrak piksel dari raster tile yang telah selesai.
- Jika job sudah pernah diunduh sebelumnya, set `jalankan=False` untuk langsung mengekstrak CSV dari data tile yang ada.

In [24]:
def main(jalankan: bool = True, ekstrak: bool = True, ulangi_error: bool = True):
    gdf = baca_semua()
    tiles, peta = buat_tile(gdf)

    # Simpan file rencana tile dan peta sampel
    tiles.to_csv(OUT_DIR / "rencana_tile.csv", index=False)
    peta.to_csv(PETA_CSV, index=False)
    gdf.drop(columns="geometry").assign(luas_derajat2=gdf.geometry.area).to_csv(OUT_DIR / "daftar_poligon.csv", index_label="sampel_id")

    if jalankan:
        db = jalankan_job(tiles, ulangi_error=ulangi_error)
    else:
        db = CsvJobDatabase(JOB_DB_PATH).read()

    hasil = None
    if ekstrak:
        hasil = ekstrak_piksel(gdf, db, peta)
    return hasil if hasil is not None else db

# EKSEKUSI PIPELINE (Ubah jalankan=True jika ingin memulai request openEO baru)
df_piksel = main(jalankan=True, ekstrak=True, ulangi_error=True)

Kelas: Sawah              | Jumlah:  50 poligon | Bounds: [np.float64(112.55), np.float64(-7.07), np.float64(112.59), np.float64(-7.06)]
Kelas: Pemukiman          | Jumlah:  50 poligon | Bounds: [np.float64(112.55), np.float64(-7.06), np.float64(112.59), np.float64(-7.04)]
Kelas: Hutan Non-Mangrove | Jumlah:  50 poligon | Bounds: [np.float64(111.21), np.float64(-8.19), np.float64(112.52), np.float64(-7.62)]
Kelas: Air                | Jumlah:  50 poligon | Bounds: [np.float64(111.21), np.float64(-7.68), np.float64(112.78), np.float64(-6.65)]
Kelas: Hutan Mangrove     | Jumlah:  50 poligon | Bounds: [np.float64(112.69), np.float64(-7.39), np.float64(113.53), np.float64(-7.14)]
------------------------------------------------------------
Total Keseluruhan Sampel: 250 Poligon
Total Grid Tile (Job)   : 97 Tile
Ukuran Tile Terbesar    : 6.0 km x 6.0 km
Total Estimasi Area     : 1,429 km²

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21444\1697055212.py:8: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf.drop(columns="geometry").assign(luas_derajat2=gdf.geometry.area).to_csv(OUT_DIR / "daftar_poligon.csv", index_label="sampel_id")

Authenticated using refresh token.
[10:50:48] >> Mengirim job tile x2250_y-142 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:50:55] >> Mengirim job tile x2251_y-142 (88 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:51:18] Progres: 0/97 (0%) | Berjalan/Antre: 0 | Belum: 95 | Gagal: 0 | 0.5 mnt
[10:51:48] Progres: 0/97 (0%) | Berjalan/Antre: 2 | Belum: 95 | Gagal: 0 | 1.0 mnt
[10:52:18] Progres: 0/97 (0%) | Berjalan/Antre: 2 | Belum: 95 | Gagal: 0 | 1.5 mnt
[10:52:48] Progres: 0/97 (0%) | Berjalan/Antre: 2 | Belum: 95 | Gagal: 0 | 2.0 mnt
[10:53:18] Progres: 0/97 (0%) | Berjalan/Antre: 2 | Belum: 95 | Gagal: 0 | 2.5 mnt
[10:53:36] >> Mengirim job tile x2251_y-141 (29 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:53:43] >> Mengirim job tile x2250_y-141 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:53:48] Progres: 2/97 (2%) | Berjalan/Antre: 0 | Belum: 94 | Gagal: 0 | 3.0 mnt
[10:53:48] [OK] Tile x2250_y-142 selesai (job j-26101903505443ff90cacc8974ffae18), mengunduh hasil...
[10:53:48] [OK] Tile x2250_y-142 berhasil terunduh.
[10:53:48] [OK] Tile x2251_y-142 selesai (job j-261019035101484c8ac17ab2ed6c1884), mengunduh hasil...
[10:53:48] [OK] Tile x2251_y-142 berhasil terunduh.
[10:54:18] Progres: 2/97 (2%) | Berjalan/Antre: 1 | Belum: 93 | Gagal: 0 | 3.5 mnt
[10:54:48] Progres: 2/97 (2%) | Berjalan/Antre: 2 | Belum: 93 | Gagal: 0 | 4.0 mnt
[10:55:18] Progres: 2/97 (2%) | Berjalan/Antre: 2 | Belum: 93 | Gagal: 0 | 4.5 mnt
[10:55:48] Progres: 2/97 (2%) | Berjalan/Antre: 2 | Belum: 93 | Gagal: 0 | 5.0 mnt
[10:56:18] Progres: 2/97 (2%) | Berjalan/Antre: 2 | Belum: 93 | Gagal: 0 | 5.5 mnt
[10:56:23] >> Mengirim job tile x2249_y-159 (13 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:56:31] >> Mengirim job tile x2249_y-158 (9 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:56:38] [OK] Tile x2251_y-141 selesai (job j-26101903534040d296ad76a0ed8de13a), mengunduh hasil...
[10:56:38] [OK] Tile x2251_y-141 berhasil terunduh.
[10:56:38] [OK] Tile x2250_y-141 selesai (job j-261019035348404186561f26181a5980), mengunduh hasil...
[10:56:38] [OK] Tile x2250_y-141 berhasil terunduh.
[10:56:48] Progres: 4/97 (4%) | Berjalan/Antre: 1 | Belum: 91 | Gagal: 0 | 6.0 mnt
[10:57:18] Progres: 4/97 (4%) | Berjalan/Antre: 2 | Belum: 91 | Gagal: 0 | 6.5 mnt
[10:57:48] Progres: 4/97 (4%) | Berjalan/Antre: 2 | Belum: 91 | Gagal: 0 | 7.0 mnt
[10:58:18] Progres: 4/97 (4%) | Berjalan/Antre: 2 | Belum: 91 | Gagal: 0 | 7.5 mnt
[10:58:48] Progres: 4/97 (4%) | Berjalan/Antre: 2 | Belum: 91 | Gagal: 0 | 8.0 mnt
[10:59:18] Progres: 4/97 (4%) | Berjalan/Antre: 2 | Belum: 91 | Gagal: 0 | 8.5 mnt
[10:59:43] >> Mengirim job tile x2248_y-159 (9 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:59:48] Progres: 6/97 (6%) | Berjalan/Antre: 0 | Belum: 91 | Gagal: 0 | 9.0 mnt
[10:59:49] >> Mengirim job tile x2248_y-158 (5 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[10:59:53] [OK] Tile x2249_y-159 selesai (job j-2610190356284e2f8e58218d42460416), mengunduh hasil...
[10:59:53] [OK] Tile x2249_y-159 berhasil terunduh.
[10:59:53] [OK] Tile x2249_y-158 selesai (job j-2610190356374820bc96e0e928e465b9), mengunduh hasil...
[10:59:53] [OK] Tile x2249_y-158 berhasil terunduh.
[11:00:18] Progres: 6/97 (6%) | Berjalan/Antre: 0 | Belum: 89 | Gagal: 0 | 9.5 mnt
[11:00:48] Progres: 6/97 (6%) | Berjalan/Antre: 2 | Belum: 89 | Gagal: 0 | 10.0 mnt
[11:01:18] Progres: 6/97 (6%) | Berjalan/Antre: 2 | Belum: 89 | Gagal: 0 | 10.5 mnt
[11:01:48] Progres: 6/97 (6%) | Berjalan/Antre: 2 | Belum: 89 | Gagal: 0 | 11.0 mnt
[11:02:18] Progres: 6/97 (6%) | Berjalan/Antre: 2 | Belum: 89 | Gagal: 0 | 11.5 mnt
[11:02:28] >> Mengirim job tile x2250_y-159 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:02:36] >> Mengirim job tile x2249_y-157 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:02:42] [OK] Tile x2248_y-159 selesai (job j-2610190359474ef891fcacbb0158deab), mengunduh hasil...
[11:02:42] [OK] Tile x2248_y-159 berhasil terunduh.
[11:02:42] [OK] Tile x2248_y-158 selesai (job j-261019035953441583f8cb56627f6771), mengunduh hasil...
[11:02:42] [OK] Tile x2248_y-158 berhasil terunduh.
[11:02:48] Progres: 8/97 (8%) | Berjalan/Antre: 0 | Belum: 87 | Gagal: 0 | 12.0 mnt
[11:03:18] Progres: 8/97 (8%) | Berjalan/Antre: 2 | Belum: 87 | Gagal: 0 | 12.5 mnt
[11:03:48] Progres: 8/97 (8%) | Berjalan/Antre: 2 | Belum: 87 | Gagal: 0 | 13.0 mnt
[11:04:18] Progres: 8/97 (8%) | Berjalan/Antre: 2 | Belum: 87 | Gagal: 0 | 13.5 mnt
[11:04:48] Progres: 8/97 (8%) | Berjalan/Antre: 2 | Belum: 87 | Gagal: 0 | 14.0 mnt
[11:05:17] >> Mengirim job tile x2250_y-158 (3 poligon)...
[11:05:18] Progres: 9/97 (9%) | Berjalan/Antre: 1 | Belum: 87 | Gagal: 0 | 14.5 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:05:23] [OK] Tile x2249_y-157 selesai (job j-261019040241424a8175ece3297bb330), mengunduh hasil...
[11:05:23] [OK] Tile x2249_y-157 berhasil terunduh.
[11:05:48] Progres: 9/97 (9%) | Berjalan/Antre: 1 | Belum: 86 | Gagal: 0 | 15.0 mnt
[11:05:54] >> Mengirim job tile x2250_y-157 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:05:59] [OK] Tile x2250_y-159 selesai (job j-2610190402344a69ac447fc5d61cbb97), mengunduh hasil...
[11:05:59] [OK] Tile x2250_y-159 berhasil terunduh.
[11:06:18] Progres: 10/97 (10%) | Berjalan/Antre: 1 | Belum: 85 | Gagal: 0 | 15.5 mnt
[11:06:48] Progres: 10/97 (10%) | Berjalan/Antre: 2 | Belum: 85 | Gagal: 0 | 16.0 mnt
[11:07:18] Progres: 10/97 (10%) | Berjalan/Antre: 2 | Belum: 85 | Gagal: 0 | 16.5 mnt
[11:07:32] >> Mengirim job tile x2249_y-156 (5 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:07:38] [OK] Tile x2250_y-158 selesai (job j-261019040521464d82a0ceaff3d5a257), mengunduh hasil...
[11:07:38] [OK] Tile x2250_y-158 berhasil terunduh.
[11:07:48] Progres: 11/97 (11%) | Berjalan/Antre: 1 | Belum: 84 | Gagal: 0 | 17.0 mnt
[11:08:18] Progres: 11/97 (11%) | Berjalan/Antre: 2 | Belum: 84 | Gagal: 0 | 17.5 mnt
[11:08:40] >> Mengirim job tile x2250_y-156 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:08:48] Progres: 12/97 (12%) | Berjalan/Antre: 1 | Belum: 84 | Gagal: 0 | 18.0 mnt
[11:08:49] [OK] Tile x2250_y-157 selesai (job j-2610190405594bfe819571dc1e2ceadf), mengunduh hasil...
[11:08:49] [OK] Tile x2250_y-157 berhasil terunduh.
[11:09:18] Progres: 12/97 (12%) | Berjalan/Antre: 1 | Belum: 83 | Gagal: 0 | 18.5 mnt
[11:09:48] Progres: 12/97 (12%) | Berjalan/Antre: 2 | Belum: 83 | Gagal: 0 | 19.0 mnt
[11:10:18] Progres: 12/97 (12%) | Berjalan/Antre: 2 | Belum: 83 | Gagal: 0 | 19.5 mnt
[11:10:22] >> Mengirim job tile x2250_y-155 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:10:28] [OK] Tile x2249_y-156 selesai (job j-2610190407354d4e8d44936d71124887), mengunduh hasil...
[11:10:28] [OK] Tile x2249_y-156 berhasil terunduh.
[11:10:48] Progres: 13/97 (13%) | Berjalan/Antre: 1 | Belum: 82 | Gagal: 0 | 20.0 mnt
[11:11:18] Progres: 13/97 (13%) | Berjalan/Antre: 2 | Belum: 82 | Gagal: 0 | 20.5 mnt
[11:11:32] >> Mengirim job tile x2249_y-155 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:11:37] [OK] Tile x2250_y-156 selesai (job j-2610190408464f3a811fb5ec3274a8b1), mengunduh hasil...
[11:11:37] [OK] Tile x2250_y-156 berhasil terunduh.
[11:11:48] Progres: 14/97 (14%) | Berjalan/Antre: 1 | Belum: 81 | Gagal: 0 | 21.0 mnt
[11:12:18] Progres: 14/97 (14%) | Berjalan/Antre: 2 | Belum: 81 | Gagal: 0 | 21.5 mnt
[11:12:40] >> Mengirim job tile x2247_y-158 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:12:46] [OK] Tile x2250_y-155 selesai (job j-2610190410264210bccc03e77fb37301), mengunduh hasil...
[11:12:46] [OK] Tile x2250_y-155 berhasil terunduh.
[11:12:48] Progres: 15/97 (15%) | Berjalan/Antre: 1 | Belum: 80 | Gagal: 0 | 22.0 mnt
[11:13:18] Progres: 15/97 (15%) | Berjalan/Antre: 2 | Belum: 80 | Gagal: 0 | 22.5 mnt
[11:13:48] Progres: 15/97 (15%) | Berjalan/Antre: 2 | Belum: 80 | Gagal: 0 | 23.0 mnt
[11:14:18] Progres: 15/97 (15%) | Berjalan/Antre: 2 | Belum: 80 | Gagal: 0 | 23.5 mnt
[11:14:19] >> Mengirim job tile x2247_y-157 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:14:25] [OK] Tile x2249_y-155 selesai (job j-261019041136431582237dda31e0139f), mengunduh hasil...
[11:14:25] [OK] Tile x2249_y-155 berhasil terunduh.
[11:14:48] Progres: 16/97 (16%) | Berjalan/Antre: 1 | Belum: 79 | Gagal: 0 | 24.0 mnt
[11:15:18] Progres: 16/97 (16%) | Berjalan/Antre: 2 | Belum: 79 | Gagal: 0 | 24.5 mnt
[11:15:27] >> Mengirim job tile x2248_y-157 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:15:35] [OK] Tile x2247_y-158 selesai (job j-26101904124540569cc3b12b689957e4), mengunduh hasil...
[11:15:35] [OK] Tile x2247_y-158 berhasil terunduh.
[11:15:48] Progres: 17/97 (18%) | Berjalan/Antre: 1 | Belum: 78 | Gagal: 0 | 25.0 mnt
[11:16:18] Progres: 17/97 (18%) | Berjalan/Antre: 2 | Belum: 78 | Gagal: 0 | 25.5 mnt
[11:16:37] >> Mengirim job tile x2248_y-160 (5 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:16:44] [OK] Tile x2247_y-157 selesai (job j-2610190414244efc8b35542211007639), mengunduh hasil...
[11:16:44] [OK] Tile x2247_y-157 berhasil terunduh.
[11:16:48] Progres: 18/97 (19%) | Berjalan/Antre: 1 | Belum: 77 | Gagal: 0 | 26.0 mnt
[11:17:15] >> Mengirim job tile x2249_y-160 (4 poligon)...
[11:17:18] Progres: 19/97 (20%) | Berjalan/Antre: 1 | Belum: 77 | Gagal: 0 | 26.5 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:17:21] [OK] Tile x2248_y-157 selesai (job j-261019041533434fac0c7750cb4411da), mengunduh hasil...
[11:17:21] [OK] Tile x2248_y-157 berhasil terunduh.
[11:17:48] Progres: 19/97 (20%) | Berjalan/Antre: 1 | Belum: 76 | Gagal: 0 | 27.0 mnt
[11:18:18] Progres: 19/97 (20%) | Berjalan/Antre: 2 | Belum: 76 | Gagal: 0 | 27.5 mnt
[11:18:48] Progres: 19/97 (20%) | Berjalan/Antre: 2 | Belum: 76 | Gagal: 0 | 28.0 mnt
[11:19:18] Progres: 19/97 (20%) | Berjalan/Antre: 2 | Belum: 76 | Gagal: 0 | 28.5 mnt
[11:19:26] >> Mengirim job tile x2250_y-160 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:19:34] >> Mengirim job tile x2245_y-159 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:19:39] [OK] Tile x2248_y-160 selesai (job j-26101904164341a68f5e0b86474657c2), mengunduh hasil...
[11:19:39] [OK] Tile x2248_y-160 berhasil terunduh.
[11:19:39] [OK] Tile x2249_y-160 selesai (job j-261019041721416b8fadaa061a8bd3f2), mengunduh hasil...
[11:19:39] [OK] Tile x2249_y-160 berhasil terunduh.
[11:19:48] Progres: 21/97 (22%) | Berjalan/Antre: 0 | Belum: 74 | Gagal: 0 | 29.0 mnt
[11:20:18] Progres: 21/97 (22%) | Berjalan/Antre: 2 | Belum: 74 | Gagal: 0 | 29.5 mnt
[11:20:49] Progres: 21/97 (22%) | Berjalan/Antre: 2 | Belum: 74 | Gagal: 0 | 30.0 mnt
[11:21:19] Progres: 21/97 (22%) | Berjalan/Antre: 2 | Belum: 74 | Gagal: 0 | 30.5 mnt
[11:21:43] >> Mengirim job tile x2245_y-158 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:21:49] Progres: 22/97 (23%) | Berjalan/Antre: 1 | Belum: 74 | Gagal: 0 | 31.0 mnt
[11:21:49] [OK] Tile x2250_y-160 selesai (job j-2610190419324a8d82c4845d8e96717a), mengunduh hasil...
[11:21:49] [OK] Tile x2250_y-160 berhasil terunduh.
[11:22:19] Progres: 22/97 (23%) | Berjalan/Antre: 1 | Belum: 73 | Gagal: 0 | 31.5 mnt
[11:22:20] >> Mengirim job tile x2246_y-159 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:22:26] [OK] Tile x2245_y-159 selesai (job j-26101904193948cda592054ee914a19b), mengunduh hasil...
[11:22:26] [OK] Tile x2245_y-159 berhasil terunduh.
[11:22:49] Progres: 23/97 (24%) | Berjalan/Antre: 1 | Belum: 72 | Gagal: 0 | 32.0 mnt
[11:23:19] Progres: 23/97 (24%) | Berjalan/Antre: 2 | Belum: 72 | Gagal: 0 | 32.5 mnt
[11:23:49] Progres: 23/97 (24%) | Berjalan/Antre: 2 | Belum: 72 | Gagal: 0 | 33.0 mnt
[11:24:19] Progres: 23/97 (24%) | Berjalan/Antre: 2 | Belum: 72 | Gagal: 0 | 33.5 mnt
[11:24:30] >> Mengirim job tile x2246_y-158 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:24:37] >> Mengirim job tile x2245_y-160 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:24:43] [OK] Tile x2245_y-158 selesai (job j-26101904214846f18889ed7861135162), mengunduh hasil...
[11:24:43] [OK] Tile x2245_y-158 berhasil terunduh.
[11:24:43] [OK] Tile x2246_y-159 selesai (job j-2610190422254df8a88d115a962a1995), mengunduh hasil...
[11:24:43] [OK] Tile x2246_y-159 berhasil terunduh.
[11:24:49] Progres: 25/97 (26%) | Berjalan/Antre: 1 | Belum: 70 | Gagal: 0 | 34.0 mnt
[11:25:19] Progres: 25/97 (26%) | Berjalan/Antre: 2 | Belum: 70 | Gagal: 0 | 34.5 mnt
[11:25:49] Progres: 25/97 (26%) | Berjalan/Antre: 2 | Belum: 70 | Gagal: 0 | 35.0 mnt
[11:26:19] Progres: 25/97 (26%) | Berjalan/Antre: 2 | Belum: 70 | Gagal: 0 | 35.5 mnt
[11:26:49] Progres: 25/97 (26%) | Berjalan/Antre: 2 | Belum: 70 | Gagal: 0 | 36.0 mnt
[11:27:18] >> Mengirim job tile x2246_y-160 (1 poligon)...
[11:27:19] Progres: 27/97 (28%) | Berjalan/Antre: 0 | Belum: 70 | Gagal: 0 | 36.5 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:27:24] >> Mengirim job tile x2238_y-164 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:27:29] [OK] Tile x2246_y-158 selesai (job j-26101904243543eda51802d9c56c2778), mengunduh hasil...
[11:27:29] [OK] Tile x2246_y-158 berhasil terunduh.
[11:27:29] [OK] Tile x2245_y-160 selesai (job j-2610190424434ce08ad47ada96cc8294), mengunduh hasil...
[11:27:29] [OK] Tile x2245_y-160 berhasil terunduh.
[11:27:49] Progres: 27/97 (28%) | Berjalan/Antre: 0 | Belum: 68 | Gagal: 0 | 37.0 mnt
[11:28:19] Progres: 27/97 (28%) | Berjalan/Antre: 2 | Belum: 68 | Gagal: 0 | 37.5 mnt
[11:28:49] Progres: 27/97 (28%) | Berjalan/Antre: 2 | Belum: 68 | Gagal: 0 | 38.0 mnt
[11:29:19] Progres: 27/97 (28%) | Berjalan/Antre: 2 | Belum: 68 | Gagal: 0 | 38.5 mnt
[11:29:33] >> Mengirim job tile x2239_y-164 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:29:39] [OK] Tile x2246_y-160 selesai (job j-261019042722421f9749f3d5ebd2d5e9), mengunduh hasil...
[11:29:39] [OK] Tile x2246_y-160 berhasil terunduh.
[11:29:49] Progres: 28/97 (29%) | Berjalan/Antre: 1 | Belum: 67 | Gagal: 0 | 39.0 mnt
[11:30:19] Progres: 28/97 (29%) | Berjalan/Antre: 2 | Belum: 67 | Gagal: 0 | 39.5 mnt
[11:30:41] >> Mengirim job tile x2235_y-158 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:30:47] [OK] Tile x2238_y-164 selesai (job j-261019042729413b9ae53e005431e818), mengunduh hasil...
[11:30:47] [OK] Tile x2238_y-164 berhasil terunduh.
[11:30:49] Progres: 29/97 (30%) | Berjalan/Antre: 1 | Belum: 66 | Gagal: 0 | 40.0 mnt
[11:31:19] Progres: 29/97 (30%) | Berjalan/Antre: 2 | Belum: 66 | Gagal: 0 | 40.5 mnt
[11:31:49] Progres: 29/97 (30%) | Berjalan/Antre: 2 | Belum: 66 | Gagal: 0 | 41.0 mnt
[11:32:19] Progres: 29/97 (30%) | Berjalan/Antre: 2 | Belum: 66 | Gagal: 0 | 41.5 mnt
[11:32:20] >> Mengirim job tile x2235_y-157 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:32:27] [OK] Tile x2239_y-164 selesai (job j-2610190429374b6c8a51b85f5f5fd78c), mengunduh hasil...
[11:32:27] [OK] Tile x2239_y-164 berhasil terunduh.
[11:32:49] Progres: 30/97 (31%) | Berjalan/Antre: 1 | Belum: 65 | Gagal: 0 | 42.0 mnt
[11:33:19] Progres: 30/97 (31%) | Berjalan/Antre: 2 | Belum: 65 | Gagal: 0 | 42.5 mnt
[11:33:29] >> Mengirim job tile x2236_y-158 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:33:35] [OK] Tile x2235_y-158 selesai (job j-2610190430464573a1f434729b8d648f), mengunduh hasil...
[11:33:35] [OK] Tile x2235_y-158 berhasil terunduh.
[11:33:49] Progres: 31/97 (32%) | Berjalan/Antre: 1 | Belum: 64 | Gagal: 0 | 43.0 mnt
[11:34:19] Progres: 31/97 (32%) | Berjalan/Antre: 2 | Belum: 64 | Gagal: 0 | 43.5 mnt
[11:34:37] >> Mengirim job tile x2236_y-157 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:34:45] [OK] Tile x2235_y-157 selesai (job j-26101904322548b6a53b8281713aa2f9), mengunduh hasil...
[11:34:45] [OK] Tile x2235_y-157 berhasil terunduh.
[11:34:49] Progres: 32/97 (33%) | Berjalan/Antre: 1 | Belum: 63 | Gagal: 0 | 44.0 mnt
[11:35:19] Progres: 32/97 (33%) | Berjalan/Antre: 2 | Belum: 63 | Gagal: 0 | 44.5 mnt
[11:35:49] Progres: 32/97 (33%) | Berjalan/Antre: 2 | Belum: 63 | Gagal: 0 | 45.0 mnt
[11:36:18] >> Mengirim job tile x2233_y-156 (2 poligon)...
[11:36:19] Progres: 33/97 (34%) | Berjalan/Antre: 1 | Belum: 63 | Gagal: 0 | 45.5 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:36:25] [OK] Tile x2236_y-158 selesai (job j-26101904333445c2820648b7318d7bac), mengunduh hasil...
[11:36:25] [OK] Tile x2236_y-158 berhasil terunduh.
[11:36:49] Progres: 33/97 (34%) | Berjalan/Antre: 1 | Belum: 62 | Gagal: 0 | 46.0 mnt
[11:37:19] Progres: 33/97 (34%) | Berjalan/Antre: 2 | Belum: 62 | Gagal: 0 | 46.5 mnt
[11:37:26] >> Mengirim job tile x2234_y-157 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:37:33] [OK] Tile x2236_y-157 selesai (job j-261019043443464a945e20bc2acff5fe), mengunduh hasil...
[11:37:33] [OK] Tile x2236_y-157 berhasil terunduh.
[11:37:49] Progres: 34/97 (35%) | Berjalan/Antre: 1 | Belum: 61 | Gagal: 0 | 47.0 mnt
[11:38:19] Progres: 34/97 (35%) | Berjalan/Antre: 2 | Belum: 61 | Gagal: 0 | 47.5 mnt
[11:38:35] >> Mengirim job tile x2234_y-156 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:38:42] [OK] Tile x2233_y-156 selesai (job j-2610190436234f30bd3c8684ee82370c), mengunduh hasil...
[11:38:42] [OK] Tile x2233_y-156 berhasil terunduh.
[11:38:49] Progres: 35/97 (36%) | Berjalan/Antre: 1 | Belum: 60 | Gagal: 0 | 48.0 mnt
[11:39:19] Progres: 35/97 (36%) | Berjalan/Antre: 2 | Belum: 60 | Gagal: 0 | 48.5 mnt
[11:39:49] Progres: 35/97 (36%) | Berjalan/Antre: 2 | Belum: 60 | Gagal: 0 | 49.0 mnt
[11:40:19] Progres: 35/97 (36%) | Berjalan/Antre: 2 | Belum: 60 | Gagal: 0 | 49.5 mnt
[11:40:46] >> Mengirim job tile x2235_y-156 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:40:49] Progres: 37/97 (38%) | Berjalan/Antre: 0 | Belum: 60 | Gagal: 0 | 50.0 mnt
[11:40:52] >> Mengirim job tile x2236_y-156 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:40:57] [OK] Tile x2234_y-157 selesai (job j-2610190437324399bfbf50e0aafcfe29), mengunduh hasil...
[11:40:57] [OK] Tile x2234_y-157 berhasil terunduh.
[11:40:57] [OK] Tile x2234_y-156 selesai (job j-261019043840462d924e682215dfb1af), mengunduh hasil...
[11:40:57] [OK] Tile x2234_y-156 berhasil terunduh.
[11:41:19] Progres: 37/97 (38%) | Berjalan/Antre: 0 | Belum: 58 | Gagal: 0 | 50.5 mnt
[11:41:49] Progres: 37/97 (38%) | Berjalan/Antre: 2 | Belum: 58 | Gagal: 0 | 51.0 mnt
[11:42:19] Progres: 37/97 (38%) | Berjalan/Antre: 2 | Belum: 58 | Gagal: 0 | 51.5 mnt
[11:42:49] Progres: 37/97 (38%) | Berjalan/Antre: 2 | Belum: 58 | Gagal: 0 | 52.0 mnt
[11:43:19] Progres: 37/97 (38%) | Berjalan/Antre: 2 | Belum: 58 | Gagal: 0 | 52.5 mnt
[11:43:33] >> Mengirim job tile x2232_y-156 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:43:40] >> Mengirim job tile x2233_y-157 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:43:45] [OK] Tile x2235_y-156 selesai (job j-26101904405040dba2c7d696fc40136a), mengunduh hasil...
[11:43:45] [OK] Tile x2235_y-156 berhasil terunduh.
[11:43:45] [OK] Tile x2236_y-156 selesai (job j-261019044057477194b26100733bca49), mengunduh hasil...
[11:43:45] [OK] Tile x2236_y-156 berhasil terunduh.
[11:43:49] Progres: 39/97 (40%) | Berjalan/Antre: 0 | Belum: 56 | Gagal: 0 | 53.0 mnt
[11:44:19] Progres: 39/97 (40%) | Berjalan/Antre: 2 | Belum: 56 | Gagal: 0 | 53.5 mnt
[11:44:49] Progres: 39/97 (40%) | Berjalan/Antre: 2 | Belum: 56 | Gagal: 0 | 54.0 mnt
[11:45:18] >> Mengirim job tile x2233_y-155 (1 poligon)...
[11:45:19] Progres: 40/97 (41%) | Berjalan/Antre: 1 | Belum: 56 | Gagal: 0 | 54.5 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[11:45:24] [OK] Tile x2232_y-156 selesai (job j-26101904433843a3bfc68652201ef0d1), mengunduh hasil...
[11:45:24] [OK] Tile x2232_y-156 berhasil terunduh.
[11:45:49] Progres: 40/97 (41%) | Berjalan/Antre: 1 | Belum: 55 | Gagal: 0 | 55.0 mnt
[12:05:27] Progres: 40/97 (41%) | Berjalan/Antre: 2 | Belum: 55 | Gagal: 0 | 74.7 mnt
[12:05:57] Progres: 40/97 (41%) | Berjalan/Antre: 2 | Belum: 55 | Gagal: 0 | 75.2 mnt
[12:06:19] >> Mengirim job tile x2234_y-158 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:06:27] >> Mengirim job tile x2224_y-154 (2 poligon)...
[12:06:27] Progres: 42/97 (43%) | Berjalan/Antre: 0 | Belum: 54 | Gagal: 0 | 75.7 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:06:32] [OK] Tile x2233_y-157 selesai (job j-2610190443454103a646d11210cf9304), mengunduh hasil...
[12:06:32] [OK] Tile x2233_y-157 berhasil terunduh.
[12:06:32] [OK] Tile x2233_y-155 selesai (job j-26101904452243de9542c11dc1935c4c), mengunduh hasil...
[12:06:32] [OK] Tile x2233_y-155 berhasil terunduh.
[12:06:57] Progres: 42/97 (43%) | Berjalan/Antre: 0 | Belum: 53 | Gagal: 0 | 76.2 mnt
[12:07:27] Progres: 42/97 (43%) | Berjalan/Antre: 2 | Belum: 53 | Gagal: 0 | 76.7 mnt
[12:07:57] Progres: 42/97 (43%) | Berjalan/Antre: 2 | Belum: 53 | Gagal: 0 | 77.2 mnt
[12:08:27] Progres: 42/97 (43%) | Berjalan/Antre: 2 | Belum: 53 | Gagal: 0 | 77.7 mnt
[12:08:36] >> Mengirim job tile x2224_y-153 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:08:42] >> Mengirim job tile x2231_y-149 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:08:47] [OK] Tile x2234_y-158 selesai (job j-26101905062446eba8561aea1e86dc9f), mengunduh hasil...
[12:08:47] [OK] Tile x2234_y-158 berhasil terunduh.
[12:08:47] [OK] Tile x2224_y-154 selesai (job j-26101905063240f6bbd8243b398b612f), mengunduh hasil...
[12:08:47] [OK] Tile x2224_y-154 berhasil terunduh.
[12:08:57] Progres: 44/97 (45%) | Berjalan/Antre: 0 | Belum: 51 | Gagal: 0 | 78.2 mnt
[12:09:27] Progres: 44/97 (45%) | Berjalan/Antre: 2 | Belum: 51 | Gagal: 0 | 78.7 mnt
[12:09:57] Progres: 44/97 (45%) | Berjalan/Antre: 2 | Belum: 51 | Gagal: 0 | 79.2 mnt
[12:10:20] >> Mengirim job tile x2248_y-140 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:10:26] >> Mengirim job tile x2249_y-145 (5 poligon)...
[12:10:27] Progres: 46/97 (47%) | Berjalan/Antre: 0 | Belum: 50 | Gagal: 0 | 79.7 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:10:32] [OK] Tile x2224_y-153 selesai (job j-26101905084042b8991a998105b81f2a), mengunduh hasil...
[12:10:32] [OK] Tile x2224_y-153 berhasil terunduh.
[12:10:32] [OK] Tile x2231_y-149 selesai (job j-2610190508474d35b30f1578da590aa5), mengunduh hasil...
[12:10:32] [OK] Tile x2231_y-149 berhasil terunduh.
[12:10:57] Progres: 46/97 (47%) | Berjalan/Antre: 0 | Belum: 49 | Gagal: 0 | 80.2 mnt
[12:11:27] Progres: 46/97 (47%) | Berjalan/Antre: 2 | Belum: 49 | Gagal: 0 | 80.7 mnt
[12:11:57] Progres: 46/97 (47%) | Berjalan/Antre: 2 | Belum: 49 | Gagal: 0 | 81.2 mnt
[12:12:27] Progres: 46/97 (47%) | Berjalan/Antre: 2 | Belum: 49 | Gagal: 0 | 81.7 mnt
[12:12:37] >> Mengirim job tile x2248_y-145 (7 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:12:43] >> Mengirim job tile x2248_y-146 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:12:48] [OK] Tile x2248_y-140 selesai (job j-2610190510244d38a78c0559df674254), mengunduh hasil...
[12:12:48] [OK] Tile x2248_y-140 berhasil terunduh.
[12:12:48] [OK] Tile x2249_y-145 selesai (job j-26101905103241d3aca8aaa30a2d11ab), mengunduh hasil...
[12:12:48] [OK] Tile x2249_y-145 berhasil terunduh.
[12:12:58] Progres: 48/97 (49%) | Berjalan/Antre: 0 | Belum: 47 | Gagal: 0 | 82.2 mnt
[12:13:28] Progres: 48/97 (49%) | Berjalan/Antre: 2 | Belum: 47 | Gagal: 0 | 82.7 mnt
[12:13:58] Progres: 48/97 (49%) | Berjalan/Antre: 2 | Belum: 47 | Gagal: 0 | 83.2 mnt
[12:14:21] >> Mengirim job tile x2252_y-144 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:14:27] [OK] Tile x2248_y-145 selesai (job j-2610190512414ccd8bb998583f61f8c3), mengunduh hasil...
[12:14:27] [OK] Tile x2248_y-145 berhasil terunduh.
[12:14:28] Progres: 49/97 (51%) | Berjalan/Antre: 1 | Belum: 46 | Gagal: 0 | 83.7 mnt
[12:14:58] Progres: 49/97 (51%) | Berjalan/Antre: 1 | Belum: 46 | Gagal: 0 | 84.2 mnt
[12:15:28] Progres: 49/97 (51%) | Berjalan/Antre: 2 | Belum: 46 | Gagal: 0 | 84.7 mnt
[12:15:29] >> Mengirim job tile x2251_y-143 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:15:35] [OK] Tile x2248_y-146 selesai (job j-26101905124849d4b35f9ab69ffb3903), mengunduh hasil...
[12:15:35] [OK] Tile x2248_y-146 berhasil terunduh.
[12:15:58] Progres: 50/97 (52%) | Berjalan/Antre: 1 | Belum: 45 | Gagal: 0 | 85.2 mnt
[12:16:28] Progres: 50/97 (52%) | Berjalan/Antre: 2 | Belum: 45 | Gagal: 0 | 85.7 mnt
[12:16:37] >> Mengirim job tile x2245_y-145 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:16:43] [OK] Tile x2252_y-144 selesai (job j-2610190514254cfd8a9be28ad21862e9), mengunduh hasil...
[12:16:43] [OK] Tile x2252_y-144 berhasil terunduh.
[12:16:58] Progres: 51/97 (53%) | Berjalan/Antre: 1 | Belum: 44 | Gagal: 0 | 86.2 mnt
[12:17:14] >> Mengirim job tile x2255_y-146 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:17:19] [OK] Tile x2251_y-143 selesai (job j-2610190515334789b86069c70d1c084d), mengunduh hasil...
[12:17:19] [OK] Tile x2251_y-143 berhasil terunduh.
[12:17:28] Progres: 52/97 (54%) | Berjalan/Antre: 1 | Belum: 43 | Gagal: 0 | 86.7 mnt
[12:17:58] Progres: 52/97 (54%) | Berjalan/Antre: 2 | Belum: 43 | Gagal: 0 | 87.2 mnt
[12:18:28] Progres: 52/97 (54%) | Berjalan/Antre: 2 | Belum: 43 | Gagal: 0 | 87.7 mnt
[12:18:58] Progres: 52/97 (54%) | Berjalan/Antre: 2 | Belum: 43 | Gagal: 0 | 88.2 mnt
[12:19:23] >> Mengirim job tile x2248_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:19:28] Progres: 54/97 (56%) | Berjalan/Antre: 0 | Belum: 43 | Gagal: 0 | 88.7 mnt
[12:19:30] >> Mengirim job tile x2248_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:19:35] [OK] Tile x2245_y-145 selesai (job j-26101905164247b0bc3745e17d554799), mengunduh hasil...
[12:19:35] [OK] Tile x2245_y-145 berhasil terunduh.
[12:19:35] [OK] Tile x2255_y-146 selesai (job j-2610190517194cf687047b2d927b018d), mengunduh hasil...
[12:19:35] [OK] Tile x2255_y-146 berhasil terunduh.
[12:19:58] Progres: 54/97 (56%) | Berjalan/Antre: 0 | Belum: 41 | Gagal: 0 | 89.2 mnt
[12:20:28] Progres: 54/97 (56%) | Berjalan/Antre: 2 | Belum: 41 | Gagal: 0 | 89.7 mnt
[12:20:58] Progres: 54/97 (56%) | Berjalan/Antre: 2 | Belum: 41 | Gagal: 0 | 90.2 mnt
[12:21:28] Progres: 54/97 (56%) | Berjalan/Antre: 2 | Belum: 41 | Gagal: 0 | 90.7 mnt
[12:21:58] Progres: 54/97 (56%) | Berjalan/Antre: 2 | Belum: 41 | Gagal: 0 | 91.2 mnt
[12:22:28] Progres: 54/97 (56%) | Berjalan/Antre: 2 | Belum: 41 | Gagal: 0 | 91.7 mnt
[12:22:41] >> Mengirim job tile x2248_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:22:46] >> Mengirim job tile x2249_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:22:52] [OK] Tile x2248_y-137 selesai (job j-2610190519284bf4b4f6db172e693aea), mengunduh hasil...
[12:22:52] [OK] Tile x2248_y-137 berhasil terunduh.
[12:22:52] [OK] Tile x2248_y-136 selesai (job j-26101905193542da889aca288d1177c3), mengunduh hasil...
[12:22:52] [OK] Tile x2248_y-136 berhasil terunduh.
[12:22:58] Progres: 56/97 (58%) | Berjalan/Antre: 0 | Belum: 39 | Gagal: 0 | 92.2 mnt
[12:23:28] Progres: 56/97 (58%) | Berjalan/Antre: 2 | Belum: 39 | Gagal: 0 | 92.7 mnt
[12:23:58] Progres: 56/97 (58%) | Berjalan/Antre: 2 | Belum: 39 | Gagal: 0 | 93.2 mnt
[12:24:25] >> Mengirim job tile x2249_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:24:28] Progres: 57/97 (59%) | Berjalan/Antre: 1 | Belum: 39 | Gagal: 0 | 93.7 mnt
[12:24:31] [OK] Tile x2248_y-135 selesai (job j-261019052244405aa69a2a5d7b207b8b), mengunduh hasil...
[12:24:31] [OK] Tile x2248_y-135 berhasil terunduh.
[12:24:58] Progres: 57/97 (59%) | Berjalan/Antre: 1 | Belum: 38 | Gagal: 0 | 94.2 mnt
[12:25:28] Progres: 57/97 (59%) | Berjalan/Antre: 2 | Belum: 38 | Gagal: 0 | 94.7 mnt
[12:25:33] >> Mengirim job tile x2250_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:25:39] [OK] Tile x2249_y-137 selesai (job j-26101905225248d0a80684bf3337412d), mengunduh hasil...
[12:25:39] [OK] Tile x2249_y-137 berhasil terunduh.
[12:25:58] Progres: 58/97 (60%) | Berjalan/Antre: 1 | Belum: 37 | Gagal: 0 | 95.2 mnt
[12:26:28] Progres: 58/97 (60%) | Berjalan/Antre: 2 | Belum: 37 | Gagal: 0 | 95.7 mnt
[12:26:58] Progres: 58/97 (60%) | Berjalan/Antre: 2 | Belum: 37 | Gagal: 0 | 96.2 mnt
[12:27:12] >> Mengirim job tile x2250_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:27:19] [OK] Tile x2249_y-136 selesai (job j-26101905242940239bbd3ef287772c0c), mengunduh hasil...
[12:27:19] [OK] Tile x2249_y-136 berhasil terunduh.
[12:27:28] Progres: 59/97 (61%) | Berjalan/Antre: 1 | Belum: 36 | Gagal: 0 | 96.7 mnt
[12:27:58] Progres: 59/97 (61%) | Berjalan/Antre: 2 | Belum: 36 | Gagal: 0 | 97.2 mnt
[12:28:21] >> Mengirim job tile x2251_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:28:27] [OK] Tile x2250_y-137 selesai (job j-261019052537448aafe8e0a886f1e1b5), mengunduh hasil...
[12:28:27] [OK] Tile x2250_y-137 berhasil terunduh.
[12:28:28] Progres: 60/97 (62%) | Berjalan/Antre: 1 | Belum: 35 | Gagal: 0 | 97.7 mnt
[12:28:58] Progres: 60/97 (62%) | Berjalan/Antre: 2 | Belum: 35 | Gagal: 0 | 98.2 mnt
[12:29:28] Progres: 60/97 (62%) | Berjalan/Antre: 2 | Belum: 35 | Gagal: 0 | 98.7 mnt
[12:29:30] >> Mengirim job tile x2251_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:29:37] [OK] Tile x2250_y-136 selesai (job j-26101905271742919dd15a44884e976b), mengunduh hasil...
[12:29:37] [OK] Tile x2250_y-136 berhasil terunduh.
[12:29:58] Progres: 61/97 (63%) | Berjalan/Antre: 1 | Belum: 34 | Gagal: 0 | 99.2 mnt
[12:30:28] Progres: 61/97 (63%) | Berjalan/Antre: 2 | Belum: 34 | Gagal: 0 | 99.7 mnt
[12:30:39] >> Mengirim job tile x2243_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:30:45] [OK] Tile x2251_y-137 selesai (job j-26101905282647428c71c54b09098983), mengunduh hasil...
[12:30:45] [OK] Tile x2251_y-137 berhasil terunduh.
[12:30:58] Progres: 62/97 (64%) | Berjalan/Antre: 1 | Belum: 33 | Gagal: 0 | 100.2 mnt
[12:31:16] >> Mengirim job tile x2243_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:31:21] [OK] Tile x2251_y-136 selesai (job j-2610190529354e0dbcbd87a77795df0b), mengunduh hasil...
[12:31:21] [OK] Tile x2251_y-136 berhasil terunduh.
[12:31:28] Progres: 63/97 (65%) | Berjalan/Antre: 1 | Belum: 32 | Gagal: 0 | 100.7 mnt
[12:31:58] Progres: 63/97 (65%) | Berjalan/Antre: 2 | Belum: 32 | Gagal: 0 | 101.2 mnt
[12:32:28] Progres: 63/97 (65%) | Berjalan/Antre: 2 | Belum: 32 | Gagal: 0 | 101.7 mnt
[12:32:58] Progres: 63/97 (65%) | Berjalan/Antre: 2 | Belum: 32 | Gagal: 0 | 102.2 mnt
[12:33:25] >> Mengirim job tile x2243_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:33:28] Progres: 65/97 (67%) | Berjalan/Antre: 0 | Belum: 32 | Gagal: 0 | 102.7 mnt
[12:33:31] >> Mengirim job tile x2243_y-134 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:33:36] [OK] Tile x2243_y-137 selesai (job j-261019053044438388056b1fea7f5ca8), mengunduh hasil...
[12:33:36] [OK] Tile x2243_y-137 berhasil terunduh.
[12:33:36] [OK] Tile x2243_y-136 selesai (job j-2610190531214456b9187071fb21bc32), mengunduh hasil...
[12:33:36] [OK] Tile x2243_y-136 berhasil terunduh.
[12:33:58] Progres: 65/97 (67%) | Berjalan/Antre: 0 | Belum: 30 | Gagal: 0 | 103.2 mnt
[12:34:28] Progres: 65/97 (67%) | Berjalan/Antre: 2 | Belum: 30 | Gagal: 0 | 103.7 mnt
[12:34:58] Progres: 65/97 (67%) | Berjalan/Antre: 2 | Belum: 30 | Gagal: 0 | 104.2 mnt
[12:35:28] Progres: 65/97 (67%) | Berjalan/Antre: 2 | Belum: 30 | Gagal: 0 | 104.7 mnt
[12:35:40] >> Mengirim job tile x2243_y-133 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:35:46] >> Mengirim job tile x2244_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:35:51] [OK] Tile x2243_y-135 selesai (job j-2610190533304dad831049e6d6f4c46d), mengunduh hasil...
[12:35:51] [OK] Tile x2243_y-135 berhasil terunduh.
[12:35:51] [OK] Tile x2243_y-134 selesai (job j-26101905333645f3bb2d1f2f9ebf957f), mengunduh hasil...
[12:35:51] [OK] Tile x2243_y-134 berhasil terunduh.
[12:35:58] Progres: 67/97 (69%) | Berjalan/Antre: 1 | Belum: 28 | Gagal: 0 | 105.2 mnt
[12:36:28] Progres: 67/97 (69%) | Berjalan/Antre: 2 | Belum: 28 | Gagal: 0 | 105.7 mnt
[12:36:58] Progres: 67/97 (69%) | Berjalan/Antre: 2 | Belum: 28 | Gagal: 0 | 106.2 mnt
[12:37:24] >> Mengirim job tile x2244_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:37:29] Progres: 68/97 (70%) | Berjalan/Antre: 1 | Belum: 28 | Gagal: 0 | 106.7 mnt
[12:37:29] [OK] Tile x2243_y-133 selesai (job j-26101905354449a487845edb66d02c0f), mengunduh hasil...
[12:37:29] [OK] Tile x2243_y-133 berhasil terunduh.
[12:37:59] Progres: 68/97 (70%) | Berjalan/Antre: 1 | Belum: 27 | Gagal: 0 | 107.2 mnt
[12:38:29] Progres: 68/97 (70%) | Berjalan/Antre: 2 | Belum: 27 | Gagal: 0 | 107.7 mnt
[12:38:31] >> Mengirim job tile x2244_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:38:38] [OK] Tile x2244_y-137 selesai (job j-2610190535514e7f966e0cbfcc1347b8), mengunduh hasil...
[12:38:38] [OK] Tile x2244_y-137 berhasil terunduh.
[12:38:59] Progres: 69/97 (71%) | Berjalan/Antre: 1 | Belum: 26 | Gagal: 0 | 108.2 mnt
[12:39:29] Progres: 69/97 (71%) | Berjalan/Antre: 2 | Belum: 26 | Gagal: 0 | 108.7 mnt
[12:39:40] >> Mengirim job tile x2244_y-134 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:39:46] [OK] Tile x2244_y-136 selesai (job j-26101905372840e3a351bbde98780cf1), mengunduh hasil...
[12:39:46] [OK] Tile x2244_y-136 berhasil terunduh.
[12:39:59] Progres: 70/97 (72%) | Berjalan/Antre: 1 | Belum: 25 | Gagal: 0 | 109.2 mnt
[12:40:18] >> Mengirim job tile x2245_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:40:22] [OK] Tile x2244_y-135 selesai (job j-2610190538364f4fbc278c557f31e598), mengunduh hasil...
[12:40:22] [OK] Tile x2244_y-135 berhasil terunduh.
[12:40:29] Progres: 71/97 (73%) | Berjalan/Antre: 1 | Belum: 24 | Gagal: 0 | 109.7 mnt
[12:40:59] Progres: 71/97 (73%) | Berjalan/Antre: 2 | Belum: 24 | Gagal: 0 | 110.2 mnt
[12:41:29] Progres: 71/97 (73%) | Berjalan/Antre: 2 | Belum: 24 | Gagal: 0 | 110.7 mnt
[12:41:59] Progres: 71/97 (73%) | Berjalan/Antre: 2 | Belum: 24 | Gagal: 0 | 111.2 mnt
[12:42:26] >> Mengirim job tile x2245_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:42:29] Progres: 73/97 (75%) | Berjalan/Antre: 0 | Belum: 24 | Gagal: 0 | 111.7 mnt
[12:42:33] >> Mengirim job tile x2245_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:42:38] [OK] Tile x2244_y-134 selesai (job j-2610190539454504b0de274ecaa4ca33), mengunduh hasil...
[12:42:38] [OK] Tile x2244_y-134 berhasil terunduh.
[12:42:38] [OK] Tile x2245_y-137 selesai (job j-26101905402349a3a6f8b71b0215626f), mengunduh hasil...
[12:42:38] [OK] Tile x2245_y-137 berhasil terunduh.
[12:42:59] Progres: 73/97 (75%) | Berjalan/Antre: 0 | Belum: 22 | Gagal: 0 | 112.2 mnt
[12:43:29] Progres: 73/97 (75%) | Berjalan/Antre: 2 | Belum: 22 | Gagal: 0 | 112.7 mnt
[12:43:59] Progres: 73/97 (75%) | Berjalan/Antre: 2 | Belum: 22 | Gagal: 0 | 113.2 mnt
[12:44:29] Progres: 73/97 (75%) | Berjalan/Antre: 2 | Belum: 22 | Gagal: 0 | 113.7 mnt
[12:44:41] >> Mengirim job tile x2245_y-134 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:44:47] [OK] Tile x2245_y-135 selesai (job j-2610190542374acdac6235bb6b03bafd), mengunduh hasil...
[12:44:47] [OK] Tile x2245_y-135 berhasil terunduh.
[12:44:59] Progres: 74/97 (76%) | Berjalan/Antre: 1 | Belum: 21 | Gagal: 0 | 114.2 mnt
[12:45:19] >> Mengirim job tile x2246_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:45:23] [OK] Tile x2245_y-136 selesai (job j-2610190542304c70a431f3328b9197e0), mengunduh hasil...
[12:45:23] [OK] Tile x2245_y-136 berhasil terunduh.
[12:45:29] Progres: 75/97 (77%) | Berjalan/Antre: 1 | Belum: 20 | Gagal: 0 | 114.7 mnt
[12:45:59] Progres: 75/97 (77%) | Berjalan/Antre: 2 | Belum: 20 | Gagal: 0 | 115.2 mnt
[12:46:29] Progres: 75/97 (77%) | Berjalan/Antre: 2 | Belum: 20 | Gagal: 0 | 115.7 mnt
[12:46:59] Progres: 75/97 (77%) | Berjalan/Antre: 2 | Belum: 20 | Gagal: 0 | 116.2 mnt
[12:47:27] >> Mengirim job tile x2246_y-136 (1 poligon)...
[12:47:29] Progres: 77/97 (79%) | Berjalan/Antre: 0 | Belum: 20 | Gagal: 0 | 116.7 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:47:33] >> Mengirim job tile x2246_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:47:39] [OK] Tile x2245_y-134 selesai (job j-2610190544454250a4acaff8bc78ab89), mengunduh hasil...
[12:47:39] [OK] Tile x2245_y-134 berhasil terunduh.
[12:47:39] [OK] Tile x2246_y-137 selesai (job j-26101905452448cda7789325910c4e6a), mengunduh hasil...
[12:47:39] [OK] Tile x2246_y-137 berhasil terunduh.
[12:47:59] Progres: 77/97 (79%) | Berjalan/Antre: 1 | Belum: 18 | Gagal: 0 | 117.2 mnt
[12:48:29] Progres: 77/97 (79%) | Berjalan/Antre: 2 | Belum: 18 | Gagal: 0 | 117.7 mnt
[12:48:59] Progres: 77/97 (79%) | Berjalan/Antre: 2 | Belum: 18 | Gagal: 0 | 118.2 mnt
[12:49:11] >> Mengirim job tile x2247_y-137 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:49:17] [OK] Tile x2246_y-135 selesai (job j-26101905473849f788d75deaf59b5c85), mengunduh hasil...
[12:49:17] [OK] Tile x2246_y-135 berhasil terunduh.
[12:49:29] Progres: 78/97 (80%) | Berjalan/Antre: 1 | Belum: 17 | Gagal: 0 | 118.7 mnt
[12:49:48] >> Mengirim job tile x2247_y-136 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:49:53] [OK] Tile x2246_y-136 selesai (job j-2610190547314775b29f6a2f32aedf08), mengunduh hasil...
[12:49:53] [OK] Tile x2246_y-136 berhasil terunduh.
[12:49:59] Progres: 79/97 (81%) | Berjalan/Antre: 1 | Belum: 16 | Gagal: 0 | 119.2 mnt
[12:50:29] Progres: 79/97 (81%) | Berjalan/Antre: 2 | Belum: 16 | Gagal: 0 | 119.7 mnt
[12:50:59] Progres: 79/97 (81%) | Berjalan/Antre: 2 | Belum: 16 | Gagal: 0 | 120.2 mnt
[12:51:26] >> Mengirim job tile x2247_y-135 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:51:29] Progres: 80/97 (82%) | Berjalan/Antre: 1 | Belum: 16 | Gagal: 0 | 120.7 mnt
[12:51:32] [OK] Tile x2247_y-137 selesai (job j-2610190549154c2fa66b6917509c6851), mengunduh hasil...
[12:51:32] [OK] Tile x2247_y-137 berhasil terunduh.
[12:51:59] Progres: 80/97 (82%) | Berjalan/Antre: 1 | Belum: 15 | Gagal: 0 | 121.2 mnt
[12:52:29] Progres: 80/97 (82%) | Berjalan/Antre: 2 | Belum: 15 | Gagal: 0 | 121.7 mnt
[12:52:34] >> Mengirim job tile x2251_y-145 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:52:41] [OK] Tile x2247_y-136 selesai (job j-26101905495343b2b81d50af5537e2db), mengunduh hasil...
[12:52:41] [OK] Tile x2247_y-136 berhasil terunduh.
[12:52:59] Progres: 81/97 (84%) | Berjalan/Antre: 1 | Belum: 14 | Gagal: 0 | 122.2 mnt
[12:53:29] Progres: 81/97 (84%) | Berjalan/Antre: 2 | Belum: 14 | Gagal: 0 | 122.7 mnt
[12:53:43] >> Mengirim job tile x2252_y-145 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:53:50] [OK] Tile x2247_y-135 selesai (job j-26101905513049d1b60f4d78827c6497), mengunduh hasil...
[12:53:50] [OK] Tile x2247_y-135 berhasil terunduh.
[12:53:59] Progres: 82/97 (85%) | Berjalan/Antre: 1 | Belum: 13 | Gagal: 0 | 123.2 mnt
[12:54:29] Progres: 82/97 (85%) | Berjalan/Antre: 2 | Belum: 13 | Gagal: 0 | 123.7 mnt
[12:54:59] Progres: 82/97 (85%) | Berjalan/Antre: 2 | Belum: 13 | Gagal: 0 | 124.2 mnt
[12:55:23] >> Mengirim job tile x2252_y-146 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:55:29] [OK] Tile x2251_y-145 selesai (job j-2610190552394ab081e0066e88f64e2c), mengunduh hasil...
[12:55:29] [OK] Tile x2251_y-145 berhasil terunduh.
[12:55:29] Progres: 83/97 (86%) | Berjalan/Antre: 1 | Belum: 12 | Gagal: 0 | 124.7 mnt
[12:55:59] Progres: 83/97 (86%) | Berjalan/Antre: 1 | Belum: 12 | Gagal: 0 | 125.2 mnt
[12:56:29] Progres: 83/97 (86%) | Berjalan/Antre: 2 | Belum: 12 | Gagal: 0 | 125.7 mnt
[12:56:30] >> Mengirim job tile x2250_y-139 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:56:37] [OK] Tile x2252_y-145 selesai (job j-2610190553484cefa4597c4c4d3d4183), mengunduh hasil...
[12:56:37] [OK] Tile x2252_y-145 berhasil terunduh.
[12:56:59] Progres: 84/97 (87%) | Berjalan/Antre: 1 | Belum: 11 | Gagal: 0 | 126.2 mnt
[12:57:29] Progres: 84/97 (87%) | Berjalan/Antre: 2 | Belum: 11 | Gagal: 0 | 126.7 mnt
[12:57:59] Progres: 84/97 (87%) | Berjalan/Antre: 2 | Belum: 11 | Gagal: 0 | 127.2 mnt
[12:58:29] Progres: 84/97 (87%) | Berjalan/Antre: 2 | Belum: 11 | Gagal: 0 | 127.7 mnt
[12:58:41] >> Mengirim job tile x2252_y-138 (4 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:58:50] >> Mengirim job tile x2251_y-139 (2 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[12:58:55] [OK] Tile x2252_y-146 selesai (job j-26101905552745e99c97b0cf89a54d9e), mengunduh hasil...
[12:58:55] [OK] Tile x2252_y-146 berhasil terunduh.
[12:58:55] [OK] Tile x2250_y-139 selesai (job j-26101905563648d599db55a2ddb83b4f), mengunduh hasil...
[12:58:55] [OK] Tile x2250_y-139 berhasil terunduh.
[12:58:59] Progres: 86/97 (89%) | Berjalan/Antre: 1 | Belum: 9 | Gagal: 0 | 128.2 mnt
[12:59:29] Progres: 86/97 (89%) | Berjalan/Antre: 2 | Belum: 9 | Gagal: 0 | 128.7 mnt
[12:59:59] Progres: 86/97 (89%) | Berjalan/Antre: 2 | Belum: 9 | Gagal: 0 | 129.2 mnt
[13:00:29] Progres: 86/97 (89%) | Berjalan/Antre: 2 | Belum: 9 | Gagal: 0 | 129.7 mnt
[13:00:59] Progres: 86/97 (89%) | Berjalan/Antre: 2 | Belum: 9 | Gagal: 0 | 130.2 mnt
[13:01:29] Progres: 86/97 (89%) | Berjalan/Antre: 2 | Belum: 9 | Gagal: 0 | 130.7 mnt
[13:01:29] >> Mengirim job tile x2249_y-140 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:01:35] [OK] Tile x2251_y-139 selesai (job j-2610190558554090b1c687d46fe6b064), mengunduh hasil...
[13:01:35] [OK] Tile x2251_y-139 berhasil terunduh.
[13:01:59] Progres: 87/97 (90%) | Berjalan/Antre: 1 | Belum: 8 | Gagal: 0 | 131.2 mnt
[13:02:06] >> Mengirim job tile x2252_y-139 (3 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:02:11] [OK] Tile x2252_y-138 selesai (job j-261019055846423680ab2c54855051ae), mengunduh hasil...
[13:02:11] [OK] Tile x2252_y-138 berhasil terunduh.
[13:02:29] Progres: 88/97 (91%) | Berjalan/Antre: 1 | Belum: 7 | Gagal: 0 | 131.7 mnt
[13:02:59] Progres: 88/97 (91%) | Berjalan/Antre: 2 | Belum: 7 | Gagal: 0 | 132.2 mnt
[13:03:29] Progres: 88/97 (91%) | Berjalan/Antre: 2 | Belum: 7 | Gagal: 0 | 132.7 mnt
[13:03:43] >> Mengirim job tile x2252_y-140 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:03:49] [OK] Tile x2249_y-140 selesai (job j-26101906013342b2909a5a9a343862d0), mengunduh hasil...
[13:03:49] [OK] Tile x2249_y-140 berhasil terunduh.
[13:03:59] Progres: 89/97 (92%) | Berjalan/Antre: 1 | Belum: 6 | Gagal: 0 | 133.2 mnt
[13:04:20] >> Mengirim job tile x2253_y-140 (1 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:04:25] [OK] Tile x2252_y-139 selesai (job j-261019060211422780369134f072cc66), mengunduh hasil...
[13:04:25] [OK] Tile x2252_y-139 berhasil terunduh.
[13:04:29] Progres: 90/97 (93%) | Berjalan/Antre: 1 | Belum: 5 | Gagal: 0 | 133.7 mnt
[13:04:59] Progres: 90/97 (93%) | Berjalan/Antre: 2 | Belum: 5 | Gagal: 0 | 134.2 mnt
[13:05:29] Progres: 90/97 (93%) | Berjalan/Antre: 2 | Belum: 5 | Gagal: 0 | 134.7 mnt
[13:05:59] Progres: 90/97 (93%) | Berjalan/Antre: 2 | Belum: 5 | Gagal: 0 | 135.2 mnt
[13:06:29] >> Mengirim job tile x2270_y-145 (4 poligon)...
[13:06:29] Progres: 92/97 (95%) | Berjalan/Antre: 0 | Belum: 5 | Gagal: 0 | 135.7 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:06:37] >> Mengirim job tile x2256_y-147 (18 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:06:41] [OK] Tile x2252_y-140 selesai (job j-2610190603484ac1b7dde350c3dada20), mengunduh hasil...
[13:06:41] [OK] Tile x2252_y-140 berhasil terunduh.
[13:06:41] [OK] Tile x2253_y-140 selesai (job j-26101906042644b19d14d1f277e9ec09), mengunduh hasil...
[13:06:41] [OK] Tile x2253_y-140 berhasil terunduh.
[13:06:59] Progres: 92/97 (95%) | Berjalan/Antre: 0 | Belum: 3 | Gagal: 0 | 136.2 mnt
[13:07:29] Progres: 92/97 (95%) | Berjalan/Antre: 2 | Belum: 3 | Gagal: 0 | 136.7 mnt
[13:07:59] Progres: 92/97 (95%) | Berjalan/Antre: 2 | Belum: 3 | Gagal: 0 | 137.2 mnt
[13:08:14] >> Mengirim job tile x2256_y-148 (19 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:08:20] >> Mengirim job tile x2253_y-143 (10 poligon)...

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:08:25] [OK] Tile x2270_y-145 selesai (job j-261019060635425d85b0e4b9bd406b89), mengunduh hasil...
[13:08:25] [OK] Tile x2270_y-145 berhasil terunduh.
[13:08:25] [OK] Tile x2256_y-147 selesai (job j-2610190606424d6585b3637626195b85), mengunduh hasil...
[13:08:25] [OK] Tile x2256_y-147 berhasil terunduh.
[13:08:29] Progres: 94/97 (97%) | Berjalan/Antre: 0 | Belum: 1 | Gagal: 0 | 137.7 mnt
[13:08:59] Progres: 94/97 (97%) | Berjalan/Antre: 2 | Belum: 1 | Gagal: 0 | 138.2 mnt
[13:09:29] Progres: 94/97 (97%) | Berjalan/Antre: 2 | Belum: 1 | Gagal: 0 | 138.7 mnt
[13:09:59] Progres: 94/97 (97%) | Berjalan/Antre: 2 | Belum: 1 | Gagal: 0 | 139.2 mnt
[13:10:29] >> Mengirim job tile x2253_y-144 (2 poligon)...
[13:10:29] Progres: 96/97 (99%) | Berjalan/Antre: 0 | Belum: 1 | Gagal: 0 | 139.7 mnt

Failed to get/parse queryables of from /collections/SENTINEL2_L2A/queryables: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

[13:10:35] [OK] Tile x2256_y-148 selesai (job j-2610190608184d23b3b8eb27b6bce50b), mengunduh hasil...
[13:10:35] [OK] Tile x2256_y-148 berhasil terunduh.
[13:10:35] [OK] Tile x2253_y-143 selesai (job j-2610190608254504a23d05bb90135646), mengunduh hasil...
[13:10:35] [OK] Tile x2253_y-143 berhasil terunduh.
[13:10:59] Progres: 96/97 (99%) | Berjalan/Antre: 0 | Belum: 0 | Gagal: 0 | 140.2 mnt
[13:11:29] Progres: 96/97 (99%) | Berjalan/Antre: 1 | Belum: 0 | Gagal: 0 | 140.7 mnt
[13:11:59] Progres: 96/97 (99%) | Berjalan/Antre: 1 | Belum: 0 | Gagal: 0 | 141.2 mnt
[13:12:29] Progres: 96/97 (99%) | Berjalan/Antre: 1 | Belum: 0 | Gagal: 0 | 141.7 mnt
[13:12:37] [OK] Tile x2253_y-144 selesai (job j-261019061033451b8d7f90bf07c002be), mengunduh hasil...
[13:12:38] [OK] Tile x2253_y-144 berhasil terunduh.
[13:12:59] Progres: 97/97 (100%) | Berjalan/Antre: 0 | Belum: 0 | Gagal: 0 | 142.2 mnt
[13:13:29] Progres: 97/97 (100%) | Berjalan/Antre: 0 | Belum: 0 | Gagal: 0 | 142.7 mnt

=== RINGKASAN STATUS JOB OPENEO ===
status
finished    97

Mengekstrak piksel dari 97 tile yang telah selesai...
[13:13:38] Tile 1/97 (x2250_y-142): 168 piksel diekstrak
[13:13:39] Tile 2/97 (x2251_y-142): 7,372 piksel diekstrak
[13:13:39] Tile 3/97 (x2251_y-141): 3,744 piksel diekstrak
[13:13:39] Tile 4/97 (x2250_y-141): 1,242 piksel diekstrak
[13:13:40] Tile 5/97 (x2249_y-159): 20,038 piksel diekstrak
[13:13:40] Tile 6/97 (x2249_y-158): 15,106 piksel diekstrak
[13:13:40] Tile 7/97 (x2248_y-159): 18,000 piksel diekstrak
[13:13:41] Tile 8/97 (x2248_y-158): 8,613 piksel diekstrak
[13:13:41] Tile 9/97 (x2250_y-159): 6,000 piksel diekstrak
[13:13:41] Tile 10/97 (x2249_y-157): 2,026 piksel diekstrak
[13:13:41] Tile 11/97 (x2250_y-158): 4,040 piksel diekstrak
[13:13:41] Tile 12/97 (x2250_y-157): 6 piksel diekstrak
[13:13:42] Tile 13/97 (x2249_y-156): 6,686 piksel diekstrak
[13:13:42] Tile 14/97 (x2250_y-156): 4,000 piksel diekstrak
[13:13:42] Tile 15/97 (x2250_y-155): 2,000 piksel diekstrak
[13:13:42] Tile 16/97 (x2249_y-155): 4,000 piksel diekstrak
[13:13:42] Tile 17/97 (x2247_y-158): 4,000 piksel diekstrak
[13:13:42] Tile 18/97 (x2247_y-157): 2,000 piksel diekstrak
[13:13:43] Tile 19/97 (x2248_y-157): 5,687 piksel diekstrak
[13:13:43] Tile 20/97 (x2248_y-160): 10,000 piksel diekstrak
[13:13:43] Tile 21/97 (x2249_y-160): 8,000 piksel diekstrak
[13:13:43] Tile 22/97 (x2250_y-160): 2,000 piksel diekstrak
[13:13:44] Tile 23/97 (x2245_y-159): 6,000 piksel diekstrak
[13:13:44] Tile 24/97 (x2245_y-158): 2,000 piksel diekstrak
[13:13:44] Tile 25/97 (x2246_y-159): 6,000 piksel diekstrak
[13:13:44] Tile 26/97 (x2246_y-158): 4,000 piksel diekstrak
[13:13:44] Tile 27/97 (x2245_y-160): 397 piksel diekstrak
[13:13:44] Tile 28/97 (x2246_y-160): 2,000 piksel diekstrak
[13:13:44] Tile 29/97 (x2238_y-164): 2,000 piksel diekstrak
[13:13:44] Tile 30/97 (x2239_y-164): 719 piksel diekstrak
[13:13:45] Tile 31/97 (x2235_y-158): 2,049 piksel diekstrak
[13:13:45] Tile 32/97 (x2235_y-157): 6,000 piksel diekstrak
[13:13:46] Tile 33/97 (x2236_y-158): 2,000 piksel diekstrak
[13:13:46] Tile 34/97 (x2236_y-157): 4,000 piksel diekstrak
[13:13:46] Tile 35/97 (x2233_y-156): 4,000 piksel diekstrak
[13:13:47] Tile 36/97 (x2234_y-157): 4,328 piksel diekstrak
[13:13:47] Tile 37/97 (x2234_y-156): 2,000 piksel diekstrak
[13:13:48] Tile 38/97 (x2235_y-156): 2,000 piksel diekstrak
[13:13:48] Tile 39/97 (x2236_y-156): 2,000 piksel diekstrak
[13:13:48] Tile 40/97 (x2232_y-156): 2,000 piksel diekstrak
[13:13:48] Tile 41/97 (x2233_y-157): 4,000 piksel diekstrak
[13:13:48] Tile 42/97 (x2233_y-155): 2,000 piksel diekstrak
[13:13:48] Tile 43/97 (x2234_y-158): 2,000 piksel diekstrak
[13:13:48] Tile 44/97 (x2224_y-154): 686 piksel diekstrak
[13:13:49] Tile 45/97 (x2224_y-153): 2,000 piksel diekstrak
[13:13:49] Tile 46/97 (x2231_y-149): 364 piksel diekstrak
[13:13:49] Tile 47/97 (x2248_y-140): 2,000 piksel diekstrak
[13:13:49] Tile 48/97 (x2249_y-145): 1,280 piksel diekstrak
[13:13:49] Tile 49/97 (x2248_y-145): 1,476 piksel diekstrak
[13:13:49] Tile 50/97 (x2248_y-146): 1,668 piksel diekstrak
[13:13:49] Tile 51/97 (x2252_y-144): 3,231 piksel diekstrak
[13:13:49] Tile 52/97 (x2251_y-143): 170 piksel diekstrak
[13:13:49] Tile 53/97 (x2245_y-145): 1,903 piksel diekstrak
[13:13:49] Tile 54/97 (x2255_y-146): 70 piksel diekstrak
[13:13:49] Tile 55/97 (x2248_y-137): 2,000 piksel diekstrak
[13:13:50] Tile 56/97 (x2248_y-136): 2,000 piksel diekstrak
[13:13:50] Tile 57/97 (x2248_y-135): 683 piksel diekstrak
[13:13:50] Tile 58/97 (x2249_y-137): 2,000 piksel diekstrak
[13:13:50] Tile 59/97 (x2249_y-136): 2,000 piksel diekstrak
[13:13:51] Tile 60/97 (x2250_y-137): 2,000 piksel diekstrak
[13:13:51] Tile 61/97 (x2250_y-136): 2,000 piksel diekstrak
[13:13:51] Tile 62/97 (x2251_y-137): 780 piksel diekstrak
[13:13:51] Tile 63/97 (x2251_y-136): 2,000 piksel diekstrak
[13:13:51] Tile 64/97 (x2243_y-137): 51 piksel diekstrak
[13:13:52] Tile 65/97 (x2243_y-136): 2,000 piksel diekstrak
[13:13:52] Tile 66/97 (x2243_y-135): 2,000 piksel diekstrak
[13:13:52] Tile 67/97 (x2243_y-134): 2,000 piksel diekstrak
[13:13:52] Tile 68/97 (x2243_y-133): 249 piksel diekstrak
[13:13:52] Tile 69/97 (x2244_y-137): 2,000 piksel diekstrak
[13:13:53] Tile 70/97 (x2244_y-136): 2,000 piksel diekstrak
[13:13:53] Tile 71/97 (x2244_y-135): 2,000 piksel diekstrak
[13:13:54] Tile 72/97 (x2244_y-134): 2,000 piksel diekstrak
[13:13:54] Tile 73/97 (x2245_y-137): 2,000 piksel diekstrak
[13:13:54] Tile 74/97 (x2245_y-136): 2,000 piksel diekstrak
[13:13:55] Tile 75/97 (x2245_y-135): 2,000 piksel diekstrak
[13:13:55] Tile 76/97 (x2245_y-134): 2,000 piksel diekstrak
[13:13:55] Tile 77/97 (x2246_y-137): 2,000 piksel diekstrak
[13:13:55] Tile 78/97 (x2246_y-136): 2,000 piksel diekstrak
[13:13:56] Tile 79/97 (x2246_y-135): 2,000 piksel diekstrak
[13:13:56] Tile 80/97 (x2247_y-137): 2,000 piksel diekstrak
[13:13:56] Tile 81/97 (x2247_y-136): 2,000 piksel diekstrak
[13:13:56] Tile 82/97 (x2247_y-135): 2,000 piksel diekstrak
[13:13:56] Tile 83/97 (x2251_y-145): 204 piksel diekstrak
[13:13:56] Tile 84/97 (x2252_y-145): 328 piksel diekstrak
[13:13:56] Tile 85/97 (x2252_y-146): 28 piksel diekstrak
[13:13:56] Tile 86/97 (x2250_y-139): 172 piksel diekstrak
[13:13:56] Tile 87/97 (x2252_y-138): 5,518 piksel diekstrak
[13:13:56] Tile 88/97 (x2251_y-139): 1,648 piksel diekstrak
[13:13:56] Tile 89/97 (x2249_y-140): 88 piksel diekstrak
[13:13:56] Tile 90/97 (x2252_y-139): 6,000 piksel diekstrak
[13:13:57] Tile 91/97 (x2252_y-140): 2,000 piksel diekstrak
[13:13:57] Tile 92/97 (x2253_y-140): 519 piksel diekstrak
[13:13:57] Tile 93/97 (x2270_y-145): 1,006 piksel diekstrak
[13:13:57] Tile 94/97 (x2256_y-147): 6,766 piksel diekstrak
[13:13:57] Tile 95/97 (x2256_y-148): 6,311 piksel diekstrak
[13:13:57] Tile 96/97 (x2253_y-143): 1,923 piksel diekstrak
[13:13:57] Tile 97/97 (x2253_y-144): 269 piksel diekstrak

[SUKSES] Dataset piksel tersimpan ke: d:\SEMESTER 5 TIF 2026\PSD\mynewbook\uts\data\csv\hasil_s2_piksel\piksel_s2.csv
Total Piksel Berlabel: 293,612
label_teks
Air                    81754
Hutan Mangrove         16275
Hutan Non-Mangrove    185815
Pemukiman               8606
Sawah                   1162

---
## Step 6: Pratinjau & Validasi Data Piksel yang Berhasil Disimpan

In [25]:
if PIKSEL_OUT.exists():
    df_hasil = pd.read_csv(PIKSEL_OUT)
    print(f"File: {PIKSEL_OUT}")
    print(f"Dimensi Data: {df_hasil.shape[0]:,} baris x {df_hasil.shape[1]} kolom")
    print("\nDistribusi Piksel per Kelas Tutupan Lahan:")
    print(df_hasil['label_teks'].value_counts())
    display(df_hasil.head(5))
else:
    print(f"File {PIKSEL_OUT} belum terbentuk. Jalankan main() untuk mengekstrak data!")

File: d:\SEMESTER 5 TIF 2026\PSD\mynewbook\uts\data\csv\hasil_s2_piksel\piksel_s2.csv
Dimensi Data: 293,612 baris x 29 kolom

Distribusi Piksel per Kelas Tutupan Lahan:
label_teks
Hutan Non-Mangrove    185815
Air                    81754
Hutan Mangrove         16275
Pemukiman               8606
Sawah                   1162
Name: count, dtype: int64

,poligon_id,poligon_no,sampel_id,tile_id,label,label_teks,px_row,px_col,lon,lat,...,B09,B11,B12,NDVI,NDWI,MNDWI,NDBI,REMI,NDMI,BSI
0,Sawah_0000,0,0,x2250_y-142,1,Sawah,229,25,112.546295,-7.068681,...,869.0,484.0,351.0,0.068259,0.045732,0.172650,-0.127928,-1.945545,0.127928,-0.005792
1,Sawah_0000,0,0,x2250_y-142,1,Sawah,229,26,112.546385,-7.068681,...,869.0,484.0,351.0,0.080808,0.047478,0.186555,-0.140320,-1.770270,0.140320,-0.004831
2,Sawah_0000,0,0,x2250_y-142,1,Sawah,229,27,112.546476,-7.068681,...,419.0,409.0,271.0,0.089860,0.012696,0.247470,-0.235514,-1.174721,0.235514,-0.041874
3,Sawah_0000,0,0,x2250_y-142,1,Sawah,229,28,112.546566,-7.068680,...,419.0,409.0,271.0,0.092437,0.000769,0.228302,-0.227573,-1.355372,0.227573,-0.048622
4,Sawah_0000,0,0,x2250_y-142,1,Sawah,229,29,112.546657,-7.068680,...,419.0,396.0,293.0,0.108878,0.008240,0.259121,-0.251418,-1.083032,0.251418,-0.069208