In [1]:
import pandas as pd

# Menampilkan 5 data teratas CSV CH4
df_ch4 = pd.read_csv("./../data/csv/CH4_gresik_timeseries.csv")
df_ch4.head()

         date          CH4
0  2025-08-24          NaN
1  2025-08-25  1867.289429
2  2025-08-26          NaN
3  2025-08-27          NaN
4  2025-08-28          NaN

In [2]:
import pandas as pd

# Menampilkan 5 data teratas CSV CO
df_co = pd.read_csv("./../data/csv/CO_gresik_timeseries.csv")
df_co.head()

         date        CO
0  2025-08-24  0.037918
1  2025-08-25  0.028240
2  2025-08-26       NaN
3  2025-08-27  0.034187
4  2025-08-28  0.027450

In [3]:
import pandas as pd

# Menampilkan 5 data teratas CSV NO2
df_no2 = pd.read_csv("./../data/csv/NO2_gresik_timeseries.csv")
df_no2.head()

         date       NO2
0  2025-08-24  0.000096
1  2025-08-25  0.000046
2  2025-08-26  0.000068
3  2025-08-27       NaN
4  2025-08-28  0.000060

In [4]:
import pandas as pd

# Menampilkan 5 data teratas CSV SO2
df_so2 = pd.read_csv("./../data/csv/SO2_gresik_timeseries.csv")
df_so2.head()

         date       SO2
0  2025-08-24  0.000347
1  2025-08-25  0.000817
2  2025-08-26 -0.000799
3  2025-08-27 -0.000513
4  2025-08-28  0.000327